// @generated by database-cli.
// Do not edit by hand.

#[allow(dead_code)]
#[allow(unused_imports)]
pub mod auth {
    use nx_db::traits::storage::StorageRecord;
    use nx_db::{insert_value, take_optional, take_required, get_optional, get_required, AttributeKind, AttributePersistence, AttributeSchema, CollectionSchema, Context, DatabaseError, EncodedField, Field, Key, Model, Patch, QuerySpec, RelationshipKind, RelationshipSchema, RelationshipSide, StaticRegistry, FIELD_ID, FIELD_SEQUENCE, FIELD_CREATED_AT, FIELD_UPDATED_AT, FIELD_PERMISSIONS};

    pub type UserId = Key<255>;

    #[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
    pub struct UserEntity {
        pub id: UserId,
        pub name: Option<String>,
        pub email: Option<String>,
        pub phone: Option<String>,
        pub status: Option<bool>,
        pub labels: Option<Vec<String>>,
        pub password_history: Option<Vec<String>>,
        pub password: Option<String>,
        pub hash: Option<String>,
        pub hash_options: Option<String>,
        pub password_update: Option<nx_db::time::OffsetDateTime>,
        pub prefs: Option<String>,
        pub registration: Option<nx_db::time::OffsetDateTime>,
        pub email_verification: Option<bool>,
        pub phone_verification: Option<bool>,
        pub reset: Option<bool>,
        pub mfa: Option<bool>,
        pub mfa_recovery_codes: Option<String>,
        pub search: Option<String>,
        pub accessed_at: Option<nx_db::time::OffsetDateTime>,
        pub sessions: Option<String>,
        pub tokens: Option<String>,
        pub authenticators: Option<String>,
        pub challenges: Option<String>,
        pub identities: Option<String>,
        pub memberships: Option<String>,
        pub targets: Option<String>,
        pub _metadata: nx_db::Metadata,
    }

    #[derive(Debug, Clone)]
    pub struct CreateUser {
        pub id: UserId,
        pub name: Option<String>,
        pub email: Option<String>,
        pub phone: Option<String>,
        pub status: Option<bool>,
        pub labels: Option<Vec<String>>,
        pub password_history: Option<Vec<String>>,
        pub password: Option<String>,
        pub hash: Option<String>,
        pub hash_options: Option<String>,
        pub password_update: Option<nx_db::time::OffsetDateTime>,
        pub prefs: Option<String>,
        pub registration: Option<nx_db::time::OffsetDateTime>,
        pub email_verification: Option<bool>,
        pub phone_verification: Option<bool>,
        pub reset: Option<bool>,
        pub mfa: Option<bool>,
        pub mfa_recovery_codes: Option<String>,
        pub search: Option<String>,
        pub accessed_at: Option<nx_db::time::OffsetDateTime>,
        pub sessions: Option<String>,
        pub tokens: Option<String>,
        pub authenticators: Option<String>,
        pub challenges: Option<String>,
        pub identities: Option<String>,
        pub memberships: Option<String>,
        pub targets: Option<String>,
        pub permissions: Vec<String>,
    }

    #[derive(Debug, Clone, Default)]
    pub struct UpdateUser {
        pub name: Patch<Option<String>>,
        pub email: Patch<Option<String>>,
        pub phone: Patch<Option<String>>,
        pub status: Patch<Option<bool>>,
        pub labels: Patch<Option<Vec<String>>>,
        pub password_history: Patch<Option<Vec<String>>>,
        pub password: Patch<Option<String>>,
        pub hash: Patch<Option<String>>,
        pub hash_options: Patch<Option<String>>,
        pub password_update: Patch<Option<nx_db::time::OffsetDateTime>>,
        pub prefs: Patch<Option<String>>,
        pub registration: Patch<Option<nx_db::time::OffsetDateTime>>,
        pub email_verification: Patch<Option<bool>>,
        pub phone_verification: Patch<Option<bool>>,
        pub reset: Patch<Option<bool>>,
        pub mfa: Patch<Option<bool>>,
        pub mfa_recovery_codes: Patch<Option<String>>,
        pub search: Patch<Option<String>>,
        pub accessed_at: Patch<Option<nx_db::time::OffsetDateTime>>,
        pub sessions: Patch<Option<String>>,
        pub tokens: Patch<Option<String>>,
        pub authenticators: Patch<Option<String>>,
        pub challenges: Patch<Option<String>>,
        pub identities: Patch<Option<String>>,
        pub memberships: Patch<Option<String>>,
        pub targets: Patch<Option<String>>,
        pub permissions: Patch<Vec<String>>,
    }

    #[derive(Debug, Clone, Copy)]
    pub struct User;
    pub const USER: User = User;

    pub const USER_ID: Field<User, UserId> = Field::new(FIELD_ID);
    pub const USER_NAME: Field<User, Option<String>> = Field::new("name");
    pub const USER_EMAIL: Field<User, Option<String>> = Field::new("email");
    pub const USER_PHONE: Field<User, Option<String>> = Field::new("phone");
    pub const USER_STATUS: Field<User, Option<bool>> = Field::new("status");
    pub const USER_LABELS: Field<User, Option<Vec<String>>> = Field::new("labels");
    pub const USER_PASSWORD_HISTORY: Field<User, Option<Vec<String>>> = Field::new("passwordHistory");
    pub const USER_PASSWORD: EncodedField<User, Option<String>> = EncodedField::new("password", encode_query_user_password);
    pub const USER_HASH: Field<User, Option<String>> = Field::new("hash");
    pub const USER_HASH_OPTIONS: Field<User, Option<String>> = Field::new("hashOptions");
    pub const USER_PASSWORD_UPDATE: Field<User, Option<nx_db::time::OffsetDateTime>> = Field::new("passwordUpdate");
    pub const USER_PREFS: Field<User, Option<String>> = Field::new("prefs");
    pub const USER_REGISTRATION: Field<User, Option<nx_db::time::OffsetDateTime>> = Field::new("registration");
    pub const USER_EMAIL_VERIFICATION: Field<User, Option<bool>> = Field::new("emailVerification");
    pub const USER_PHONE_VERIFICATION: Field<User, Option<bool>> = Field::new("phoneVerification");
    pub const USER_RESET: Field<User, Option<bool>> = Field::new("reset");
    pub const USER_MFA: Field<User, Option<bool>> = Field::new("mfa");
    pub const USER_MFA_RECOVERY_CODES: EncodedField<User, Option<String>> = EncodedField::new("mfaRecoveryCodes", encode_query_user_mfa_recovery_codes);
    pub const USER_SEARCH: EncodedField<User, Option<String>> = EncodedField::new("search", encode_query_user_search);
    pub const USER_ACCESSED_AT: Field<User, Option<nx_db::time::OffsetDateTime>> = Field::new("accessedAt");
    pub const USER_SESSIONS: Field<User, Option<String>> = Field::new("sessions");
    pub const USER_TOKENS: Field<User, Option<String>> = Field::new("tokens");
    pub const USER_AUTHENTICATORS: Field<User, Option<String>> = Field::new("authenticators");
    pub const USER_CHALLENGES: Field<User, Option<String>> = Field::new("challenges");
    pub const USER_IDENTITIES: Field<User, Option<String>> = Field::new("identities");
    pub const USER_MEMBERSHIPS: Field<User, Option<String>> = Field::new("memberships");
    pub const USER_TARGETS: Field<User, Option<String>> = Field::new("targets");

    fn encode_user_password(value: Option<String>) -> Result<Option<String>, DatabaseError> {
        if let Some(value) = value {
            let value = crate::filters::encrypt(value)?;
            Ok(Some(value))
        } else {
            Ok(None)
        }
    }

    fn encode_query_user_password(value: Option<String>) -> Result<nx_db::traits::storage::StorageValue, DatabaseError> {
        if let Some(value) = value {
            Ok(nx_db::IntoStorage::into_storage(crate::filters::encrypt(value)?))
        } else {
            Ok(nx_db::traits::storage::StorageValue::Null)
        }
    }

    fn decode_user_password(value: Option<String>) -> Result<Option<String>, DatabaseError> {
        if let Some(value) = value {
            let value = crate::filters::decrypt(value)?;
            Ok(Some(value))
        } else {
            Ok(None)
        }
    }

    fn encode_user_mfa_recovery_codes(value: Option<String>) -> Result<Option<String>, DatabaseError> {
        if let Some(value) = value {
            let value = crate::filters::encrypt(value)?;
            Ok(Some(value))
        } else {
            Ok(None)
        }
    }

    fn encode_query_user_mfa_recovery_codes(value: Option<String>) -> Result<nx_db::traits::storage::StorageValue, DatabaseError> {
        if let Some(value) = value {
            Ok(nx_db::IntoStorage::into_storage(crate::filters::encrypt(value)?))
        } else {
            Ok(nx_db::traits::storage::StorageValue::Null)
        }
    }

    fn decode_user_mfa_recovery_codes(value: Option<String>) -> Result<Option<String>, DatabaseError> {
        if let Some(value) = value {
            let value = crate::filters::decrypt(value)?;
            Ok(Some(value))
        } else {
            Ok(None)
        }
    }

    fn encode_user_search(value: Option<String>) -> Result<Option<String>, DatabaseError> {
        if let Some(value) = value {
            let value = crate::filters::normalize_search(value)?;
            Ok(Some(value))
        } else {
            Ok(None)
        }
    }

    fn encode_query_user_search(value: Option<String>) -> Result<nx_db::traits::storage::StorageValue, DatabaseError> {
        if let Some(value) = value {
            Ok(nx_db::IntoStorage::into_storage(crate::filters::normalize_search(value)?))
        } else {
            Ok(nx_db::traits::storage::StorageValue::Null)
        }
    }

    fn decode_user_search(value: Option<String>) -> Result<Option<String>, DatabaseError> {
        if let Some(value) = value {
            let value = crate::filters::identity(value)?;
            Ok(Some(value))
        } else {
            Ok(None)
        }
    }

    const USERS_ATTRIBUTES: &[AttributeSchema] = &[
        AttributeSchema {
            id: "name",
            column: "name",
            kind: AttributeKind::String,
            required: false,
            array: false,
            length: Some(256),
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: None,
        },
        AttributeSchema {
            id: "email",
            column: "email",
            kind: AttributeKind::String,
            required: false,
            array: false,
            length: Some(320),
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: None,
        },
        AttributeSchema {
            id: "phone",
            column: "phone",
            kind: AttributeKind::String,
            required: false,
            array: false,
            length: Some(16),
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: None,
        },
        AttributeSchema {
            id: "status",
            column: "status",
            kind: AttributeKind::Boolean,
            required: false,
            array: false,
            length: None,
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: None,
        },
        AttributeSchema {
            id: "labels",
            column: "labels",
            kind: AttributeKind::String,
            required: false,
            array: true,
            length: Some(128),
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: None,
        },
        AttributeSchema {
            id: "passwordHistory",
            column: "passwordHistory",
            kind: AttributeKind::String,
            required: false,
            array: true,
            length: None,
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: None,
        },
        AttributeSchema {
            id: "password",
            column: "password",
            kind: AttributeKind::String,
            required: false,
            array: false,
            length: None,
            persistence: AttributePersistence::Persisted,
            filters: &["encrypt"],
            relationship: None,
        },
        AttributeSchema {
            id: "hash",
            column: "hash",
            kind: AttributeKind::String,
            required: false,
            array: false,
            length: Some(256),
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: None,
        },
        AttributeSchema {
            id: "hashOptions",
            column: "hashOptions",
            kind: AttributeKind::Json,
            required: false,
            array: false,
            length: None,
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: None,
        },
        AttributeSchema {
            id: "passwordUpdate",
            column: "passwordUpdate",
            kind: AttributeKind::Timestamp,
            required: false,
            array: false,
            length: None,
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: None,
        },
        AttributeSchema {
            id: "prefs",
            column: "prefs",
            kind: AttributeKind::Json,
            required: false,
            array: false,
            length: None,
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: None,
        },
        AttributeSchema {
            id: "registration",
            column: "registration",
            kind: AttributeKind::Timestamp,
            required: false,
            array: false,
            length: None,
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: None,
        },
        AttributeSchema {
            id: "emailVerification",
            column: "emailVerification",
            kind: AttributeKind::Boolean,
            required: false,
            array: false,
            length: None,
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: None,
        },
        AttributeSchema {
            id: "phoneVerification",
            column: "phoneVerification",
            kind: AttributeKind::Boolean,
            required: false,
            array: false,
            length: None,
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: None,
        },
        AttributeSchema {
            id: "reset",
            column: "reset",
            kind: AttributeKind::Boolean,
            required: false,
            array: false,
            length: None,
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: None,
        },
        AttributeSchema {
            id: "mfa",
            column: "mfa",
            kind: AttributeKind::Boolean,
            required: false,
            array: false,
            length: None,
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: None,
        },
        AttributeSchema {
            id: "mfaRecoveryCodes",
            column: "mfaRecoveryCodes",
            kind: AttributeKind::String,
            required: false,
            array: false,
            length: None,
            persistence: AttributePersistence::Persisted,
            filters: &["encrypt"],
            relationship: None,
        },
        AttributeSchema {
            id: "search",
            column: "search",
            kind: AttributeKind::String,
            required: false,
            array: false,
            length: None,
            persistence: AttributePersistence::Persisted,
            filters: &["userSearch"],
            relationship: None,
        },
        AttributeSchema {
            id: "accessedAt",
            column: "accessedAt",
            kind: AttributeKind::Timestamp,
            required: false,
            array: false,
            length: None,
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: None,
        },
        AttributeSchema {
            id: "sessions",
            column: "sessions",
            kind: AttributeKind::Relationship,
            required: false,
            array: false,
            length: None,
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: Some(nx_db::RelationshipSchema {
                related_collection: "sessions",
                kind: nx_db::RelationshipKind::OneToMany,
                side: nx_db::RelationshipSide::Parent,
                two_way: true,
                two_way_key: Some("user"),
                on_delete: nx_db::OnDeleteAction::Restrict,
            }),
        },
        AttributeSchema {
            id: "tokens",
            column: "tokens",
            kind: AttributeKind::Relationship,
            required: false,
            array: false,
            length: None,
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: Some(nx_db::RelationshipSchema {
                related_collection: "tokens",
                kind: nx_db::RelationshipKind::OneToMany,
                side: nx_db::RelationshipSide::Parent,
                two_way: true,
                two_way_key: Some("user"),
                on_delete: nx_db::OnDeleteAction::Restrict,
            }),
        },
        AttributeSchema {
            id: "authenticators",
            column: "authenticators",
            kind: AttributeKind::Relationship,
            required: false,
            array: false,
            length: None,
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: Some(nx_db::RelationshipSchema {
                related_collection: "authenticators",
                kind: nx_db::RelationshipKind::OneToMany,
                side: nx_db::RelationshipSide::Parent,
                two_way: true,
                two_way_key: Some("user"),
                on_delete: nx_db::OnDeleteAction::Restrict,
            }),
        },
        AttributeSchema {
            id: "challenges",
            column: "challenges",
            kind: AttributeKind::Relationship,
            required: false,
            array: false,
            length: None,
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: Some(nx_db::RelationshipSchema {
                related_collection: "challenges",
                kind: nx_db::RelationshipKind::OneToMany,
                side: nx_db::RelationshipSide::Parent,
                two_way: true,
                two_way_key: Some("user"),
                on_delete: nx_db::OnDeleteAction::Restrict,
            }),
        },
        AttributeSchema {
            id: "identities",
            column: "identities",
            kind: AttributeKind::Relationship,
            required: false,
            array: false,
            length: None,
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: Some(nx_db::RelationshipSchema {
                related_collection: "identities",
                kind: nx_db::RelationshipKind::OneToMany,
                side: nx_db::RelationshipSide::Parent,
                two_way: true,
                two_way_key: Some("user"),
                on_delete: nx_db::OnDeleteAction::Restrict,
            }),
        },
        AttributeSchema {
            id: "memberships",
            column: "memberships",
            kind: AttributeKind::Relationship,
            required: false,
            array: false,
            length: None,
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: Some(nx_db::RelationshipSchema {
                related_collection: "memberships",
                kind: nx_db::RelationshipKind::OneToMany,
                side: nx_db::RelationshipSide::Parent,
                two_way: true,
                two_way_key: Some("user"),
                on_delete: nx_db::OnDeleteAction::Restrict,
            }),
        },
        AttributeSchema {
            id: "targets",
            column: "targets",
            kind: AttributeKind::Relationship,
            required: false,
            array: false,
            length: None,
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: Some(nx_db::RelationshipSchema {
                related_collection: "targets",
                kind: nx_db::RelationshipKind::OneToMany,
                side: nx_db::RelationshipSide::Parent,
                two_way: true,
                two_way_key: Some("user"),
                on_delete: nx_db::OnDeleteAction::Restrict,
            }),
        },
    ];
    const USERS_INDEXES: &[nx_db::IndexSchema] = &[
        nx_db::IndexSchema {
            id: "_key_email",
            kind: nx_db::IndexKind::Unique,
            attributes: &["email"],
            orders: &[nx_db::Order::Asc],
        },
        nx_db::IndexSchema {
            id: "_key_phone",
            kind: nx_db::IndexKind::Unique,
            attributes: &["phone"],
            orders: &[nx_db::Order::Asc],
        },
        nx_db::IndexSchema {
            id: "_key_search",
            kind: nx_db::IndexKind::FullText,
            attributes: &["search"],
            orders: &[],
        },
    ];
    pub static USERS_SCHEMA: CollectionSchema = CollectionSchema { id: "users", name: "Users", document_security: true, enabled: true, permissions: &["create(\"any\")"], attributes: USERS_ATTRIBUTES, indexes: USERS_INDEXES };
    impl User {
        pub const ID: Field<User, UserId> = Field::new(FIELD_ID);
        pub const NAME: Field<User, Option<String>> = Field::new("name");
        pub const EMAIL: Field<User, Option<String>> = Field::new("email");
        pub const PHONE: Field<User, Option<String>> = Field::new("phone");
        pub const STATUS: Field<User, Option<bool>> = Field::new("status");
        pub const LABELS: Field<User, Option<Vec<String>>> = Field::new("labels");
        pub const PASSWORD_HISTORY: Field<User, Option<Vec<String>>> = Field::new("passwordHistory");
        pub const PASSWORD: EncodedField<User, Option<String>> = EncodedField::new("password", encode_query_user_password);
        pub const HASH: Field<User, Option<String>> = Field::new("hash");
        pub const HASH_OPTIONS: Field<User, Option<String>> = Field::new("hashOptions");
        pub const PASSWORD_UPDATE: Field<User, Option<nx_db::time::OffsetDateTime>> = Field::new("passwordUpdate");
        pub const PREFS: Field<User, Option<String>> = Field::new("prefs");
        pub const REGISTRATION: Field<User, Option<nx_db::time::OffsetDateTime>> = Field::new("registration");
        pub const EMAIL_VERIFICATION: Field<User, Option<bool>> = Field::new("emailVerification");
        pub const PHONE_VERIFICATION: Field<User, Option<bool>> = Field::new("phoneVerification");
        pub const RESET: Field<User, Option<bool>> = Field::new("reset");
        pub const MFA: Field<User, Option<bool>> = Field::new("mfa");
        pub const MFA_RECOVERY_CODES: EncodedField<User, Option<String>> = EncodedField::new("mfaRecoveryCodes", encode_query_user_mfa_recovery_codes);
        pub const SEARCH: EncodedField<User, Option<String>> = EncodedField::new("search", encode_query_user_search);
        pub const ACCESSED_AT: Field<User, Option<nx_db::time::OffsetDateTime>> = Field::new("accessedAt");
        pub const SESSIONS: Field<User, Option<String>> = Field::new("sessions");
        pub const TOKENS: Field<User, Option<String>> = Field::new("tokens");
        pub const AUTHENTICATORS: Field<User, Option<String>> = Field::new("authenticators");
        pub const CHALLENGES: Field<User, Option<String>> = Field::new("challenges");
        pub const IDENTITIES: Field<User, Option<String>> = Field::new("identities");
        pub const MEMBERSHIPS: Field<User, Option<String>> = Field::new("memberships");
        pub const TARGETS: Field<User, Option<String>> = Field::new("targets");
    }
    nx_db::impl_model! { name: User, id: UserId, entity: UserEntity, create: CreateUser, update: UpdateUser, schema: USERS_SCHEMA, fields: {                 "name" => name : Option<String>,                 "email" => email : Option<String>,                 "phone" => phone : Option<String>,                 "status" => status : Option<bool>,                 "labels" => labels : Option<Vec<String>>,                 "passwordHistory" => password_history : Option<Vec<String>>,                 "password" => password : Option<String> [encode_user_password, decode_user_password],                 "hash" => hash : Option<String>,                 "hashOptions" => hash_options : Option<String>,                 "passwordUpdate" => password_update : Option<nx_db::time::OffsetDateTime>,                 "prefs" => prefs : Option<String>,                 "registration" => registration : Option<nx_db::time::OffsetDateTime>,                 "emailVerification" => email_verification : Option<bool>,                 "phoneVerification" => phone_verification : Option<bool>,                 "reset" => reset : Option<bool>,                 "mfa" => mfa : Option<bool>,                 "mfaRecoveryCodes" => mfa_recovery_codes : Option<String> [encode_user_mfa_recovery_codes, decode_user_mfa_recovery_codes],                 "search" => search : Option<String> [encode_user_search, decode_user_search],                 "accessedAt" => accessed_at : Option<nx_db::time::OffsetDateTime>,                 "sessions" => sessions : Option<String>,                 "tokens" => tokens : Option<String>,                 "authenticators" => authenticators : Option<String>,                 "challenges" => challenges : Option<String>,                 "identities" => identities : Option<String>,                 "memberships" => memberships : Option<String>,                 "targets" => targets : Option<String> } }
    pub type TeamId = Key<255>;

    #[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
    pub struct TeamEntity {
        pub id: TeamId,
        pub name: Option<String>,
        pub total: Option<i64>,
        pub search: Option<String>,
        pub prefs: Option<String>,
        pub memberships: Option<String>,
        pub _metadata: nx_db::Metadata,
    }

    #[derive(Debug, Clone)]
    pub struct CreateTeam {
        pub id: TeamId,
        pub name: Option<String>,
        pub total: Option<i64>,
        pub search: Option<String>,
        pub prefs: Option<String>,
        pub memberships: Option<String>,
        pub permissions: Vec<String>,
    }

    #[derive(Debug, Clone, Default)]
    pub struct UpdateTeam {
        pub name: Patch<Option<String>>,
        pub total: Patch<Option<i64>>,
        pub search: Patch<Option<String>>,
        pub prefs: Patch<Option<String>>,
        pub memberships: Patch<Option<String>>,
        pub permissions: Patch<Vec<String>>,
    }

    #[derive(Debug, Clone, Copy)]
    pub struct Team;
    pub const TEAM: Team = Team;

    pub const TEAM_ID: Field<Team, TeamId> = Field::new(FIELD_ID);
    pub const TEAM_NAME: Field<Team, Option<String>> = Field::new("name");
    pub const TEAM_TOTAL: Field<Team, Option<i64>> = Field::new("total");
    pub const TEAM_SEARCH: Field<Team, Option<String>> = Field::new("search");
    pub const TEAM_PREFS: Field<Team, Option<String>> = Field::new("prefs");
    pub const TEAM_MEMBERSHIPS: Field<Team, Option<String>> = Field::new("memberships");

    const TEAMS_ATTRIBUTES: &[AttributeSchema] = &[
        AttributeSchema {
            id: "name",
            column: "name",
            kind: AttributeKind::String,
            required: false,
            array: false,
            length: Some(128),
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: None,
        },
        AttributeSchema {
            id: "total",
            column: "total",
            kind: AttributeKind::Integer,
            required: false,
            array: false,
            length: None,
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: None,
        },
        AttributeSchema {
            id: "search",
            column: "search",
            kind: AttributeKind::String,
            required: false,
            array: false,
            length: None,
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: None,
        },
        AttributeSchema {
            id: "prefs",
            column: "prefs",
            kind: AttributeKind::Json,
            required: false,
            array: false,
            length: None,
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: None,
        },
        AttributeSchema {
            id: "memberships",
            column: "memberships",
            kind: AttributeKind::Relationship,
            required: false,
            array: false,
            length: None,
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: Some(nx_db::RelationshipSchema {
                related_collection: "memberships",
                kind: nx_db::RelationshipKind::OneToMany,
                side: nx_db::RelationshipSide::Parent,
                two_way: true,
                two_way_key: Some("team"),
                on_delete: nx_db::OnDeleteAction::Restrict,
            }),
        },
    ];
    const TEAMS_INDEXES: &[nx_db::IndexSchema] = &[
        nx_db::IndexSchema {
            id: "_key_search",
            kind: nx_db::IndexKind::FullText,
            attributes: &["search"],
            orders: &[],
        },
    ];
    pub static TEAMS_SCHEMA: CollectionSchema = CollectionSchema { id: "teams", name: "Teams", document_security: true, enabled: true, permissions: &["create(\"any\")"], attributes: TEAMS_ATTRIBUTES, indexes: TEAMS_INDEXES };
    impl Team {
        pub const ID: Field<Team, TeamId> = Field::new(FIELD_ID);
        pub const NAME: Field<Team, Option<String>> = Field::new("name");
        pub const TOTAL: Field<Team, Option<i64>> = Field::new("total");
        pub const SEARCH: Field<Team, Option<String>> = Field::new("search");
        pub const PREFS: Field<Team, Option<String>> = Field::new("prefs");
        pub const MEMBERSHIPS: Field<Team, Option<String>> = Field::new("memberships");
    }
    nx_db::impl_model! { name: Team, id: TeamId, entity: TeamEntity, create: CreateTeam, update: UpdateTeam, schema: TEAMS_SCHEMA, fields: {                 "name" => name : Option<String>,                 "total" => total : Option<i64>,                 "search" => search : Option<String>,                 "prefs" => prefs : Option<String>,                 "memberships" => memberships : Option<String> } }
    pub type SessionId = Key<255>;

    #[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
    pub struct SessionEntity {
        pub id: SessionId,
        pub user_internal_id: i64,
        pub user_id: Option<String>,
        pub provider: Option<String>,
        pub provider_uid: Option<String>,
        pub secret: Option<String>,
        pub user_agent: Option<String>,
        pub ip: Option<String>,
        pub expire: nx_db::time::OffsetDateTime,
        pub user: Option<String>,
        pub _metadata: nx_db::Metadata,
    }

    #[derive(Debug, Clone)]
    pub struct CreateSession {
        pub id: SessionId,
        pub user_internal_id: i64,
        pub user_id: Option<String>,
        pub provider: Option<String>,
        pub provider_uid: Option<String>,
        pub secret: Option<String>,
        pub user_agent: Option<String>,
        pub ip: Option<String>,
        pub expire: nx_db::time::OffsetDateTime,
        pub user: Option<String>,
        pub permissions: Vec<String>,
    }

    #[derive(Debug, Clone, Default)]
    pub struct UpdateSession {
        pub user_internal_id: Patch<i64>,
        pub user_id: Patch<Option<String>>,
        pub provider: Patch<Option<String>>,
        pub provider_uid: Patch<Option<String>>,
        pub secret: Patch<Option<String>>,
        pub user_agent: Patch<Option<String>>,
        pub ip: Patch<Option<String>>,
        pub expire: Patch<nx_db::time::OffsetDateTime>,
        pub user: Patch<Option<String>>,
        pub permissions: Patch<Vec<String>>,
    }

    #[derive(Debug, Clone, Copy)]
    pub struct Session;
    pub const SESSION: Session = Session;

    pub const SESSION_ID: Field<Session, SessionId> = Field::new(FIELD_ID);
    pub const SESSION_USER_INTERNAL_ID: Field<Session, i64> = Field::new("userInternalId");
    pub const SESSION_USER_ID: Field<Session, Option<String>> = Field::new("userId");
    pub const SESSION_PROVIDER: Field<Session, Option<String>> = Field::new("provider");
    pub const SESSION_PROVIDER_UID: Field<Session, Option<String>> = Field::new("providerUid");
    pub const SESSION_SECRET: EncodedField<Session, Option<String>> = EncodedField::new("secret", encode_query_session_secret);
    pub const SESSION_USER_AGENT: Field<Session, Option<String>> = Field::new("userAgent");
    pub const SESSION_IP: Field<Session, Option<String>> = Field::new("ip");
    pub const SESSION_EXPIRE: Field<Session, nx_db::time::OffsetDateTime> = Field::new("expire");
    pub const SESSION_USER: Field<Session, Option<String>> = Field::new("user");

    fn encode_session_secret(value: Option<String>) -> Result<Option<String>, DatabaseError> {
        if let Some(value) = value {
            let value = crate::filters::encrypt(value)?;
            Ok(Some(value))
        } else {
            Ok(None)
        }
    }

    fn encode_query_session_secret(value: Option<String>) -> Result<nx_db::traits::storage::StorageValue, DatabaseError> {
        if let Some(value) = value {
            Ok(nx_db::IntoStorage::into_storage(crate::filters::encrypt(value)?))
        } else {
            Ok(nx_db::traits::storage::StorageValue::Null)
        }
    }

    fn decode_session_secret(value: Option<String>) -> Result<Option<String>, DatabaseError> {
        if let Some(value) = value {
            let value = crate::filters::decrypt(value)?;
            Ok(Some(value))
        } else {
            Ok(None)
        }
    }

    const SESSIONS_ATTRIBUTES: &[AttributeSchema] = &[
        AttributeSchema {
            id: "userInternalId",
            column: "userInternalId",
            kind: AttributeKind::Integer,
            required: true,
            array: false,
            length: None,
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: None,
        },
        AttributeSchema {
            id: "userId",
            column: "userId",
            kind: AttributeKind::String,
            required: false,
            array: false,
            length: Some(255),
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: None,
        },
        AttributeSchema {
            id: "provider",
            column: "provider",
            kind: AttributeKind::String,
            required: false,
            array: false,
            length: Some(128),
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: None,
        },
        AttributeSchema {
            id: "providerUid",
            column: "providerUid",
            kind: AttributeKind::String,
            required: false,
            array: false,
            length: Some(2048),
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: None,
        },
        AttributeSchema {
            id: "secret",
            column: "secret",
            kind: AttributeKind::String,
            required: false,
            array: false,
            length: Some(512),
            persistence: AttributePersistence::Persisted,
            filters: &["encrypt"],
            relationship: None,
        },
        AttributeSchema {
            id: "userAgent",
            column: "userAgent",
            kind: AttributeKind::String,
            required: false,
            array: false,
            length: None,
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: None,
        },
        AttributeSchema {
            id: "ip",
            column: "ip",
            kind: AttributeKind::String,
            required: false,
            array: false,
            length: Some(45),
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: None,
        },
        AttributeSchema {
            id: "expire",
            column: "expire",
            kind: AttributeKind::Timestamp,
            required: true,
            array: false,
            length: None,
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: None,
        },
        AttributeSchema {
            id: "user",
            column: "user",
            kind: AttributeKind::Relationship,
            required: false,
            array: false,
            length: None,
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: Some(nx_db::RelationshipSchema {
                related_collection: "users",
                kind: nx_db::RelationshipKind::ManyToOne,
                side: nx_db::RelationshipSide::Child,
                two_way: true,
                two_way_key: Some("sessions"),
                on_delete: nx_db::OnDeleteAction::Cascade,
            }),
        },
    ];
    const SESSIONS_INDEXES: &[nx_db::IndexSchema] = &[
    ];
    pub static SESSIONS_SCHEMA: CollectionSchema = CollectionSchema { id: "sessions", name: "Sessions", document_security: true, enabled: true, permissions: &["create(\"any\")"], attributes: SESSIONS_ATTRIBUTES, indexes: SESSIONS_INDEXES };
    impl Session {
        pub const ID: Field<Session, SessionId> = Field::new(FIELD_ID);
        pub const USER_INTERNAL_ID: Field<Session, i64> = Field::new("userInternalId");
        pub const USER_ID: Field<Session, Option<String>> = Field::new("userId");
        pub const PROVIDER: Field<Session, Option<String>> = Field::new("provider");
        pub const PROVIDER_UID: Field<Session, Option<String>> = Field::new("providerUid");
        pub const SECRET: EncodedField<Session, Option<String>> = EncodedField::new("secret", encode_query_session_secret);
        pub const USER_AGENT: Field<Session, Option<String>> = Field::new("userAgent");
        pub const IP: Field<Session, Option<String>> = Field::new("ip");
        pub const EXPIRE: Field<Session, nx_db::time::OffsetDateTime> = Field::new("expire");
        pub const USER: Field<Session, Option<String>> = Field::new("user");
    }
    nx_db::impl_model! { name: Session, id: SessionId, entity: SessionEntity, create: CreateSession, update: UpdateSession, schema: SESSIONS_SCHEMA, fields: {                 "userInternalId" => user_internal_id : i64 :required,                 "userId" => user_id : Option<String>,                 "provider" => provider : Option<String>,                 "providerUid" => provider_uid : Option<String>,                 "secret" => secret : Option<String> [encode_session_secret, decode_session_secret],                 "userAgent" => user_agent : Option<String>,                 "ip" => ip : Option<String>,                 "expire" => expire : nx_db::time::OffsetDateTime :required,                 "user" => user : Option<String> } }
    pub type TokenId = Key<255>;

    #[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
    pub struct TokenEntity {
        pub id: TokenId,
        pub user_internal_id: i64,
        pub user_id: Option<String>,
        pub kind: i64,
        pub secret: Option<String>,
        pub expire: Option<nx_db::time::OffsetDateTime>,
        pub user: Option<String>,
        pub _metadata: nx_db::Metadata,
    }

    #[derive(Debug, Clone)]
    pub struct CreateToken {
        pub id: TokenId,
        pub user_internal_id: i64,
        pub user_id: Option<String>,
        pub kind: i64,
        pub secret: Option<String>,
        pub expire: Option<nx_db::time::OffsetDateTime>,
        pub user: Option<String>,
        pub permissions: Vec<String>,
    }

    #[derive(Debug, Clone, Default)]
    pub struct UpdateToken {
        pub user_internal_id: Patch<i64>,
        pub user_id: Patch<Option<String>>,
        pub kind: Patch<i64>,
        pub secret: Patch<Option<String>>,
        pub expire: Patch<Option<nx_db::time::OffsetDateTime>>,
        pub user: Patch<Option<String>>,
        pub permissions: Patch<Vec<String>>,
    }

    #[derive(Debug, Clone, Copy)]
    pub struct Token;
    pub const TOKEN: Token = Token;

    pub const TOKEN_ID: Field<Token, TokenId> = Field::new(FIELD_ID);
    pub const TOKEN_USER_INTERNAL_ID: Field<Token, i64> = Field::new("userInternalId");
    pub const TOKEN_USER_ID: Field<Token, Option<String>> = Field::new("userId");
    pub const TOKEN_KIND: Field<Token, i64> = Field::new("kind");
    pub const TOKEN_SECRET: EncodedField<Token, Option<String>> = EncodedField::new("secret", encode_query_token_secret);
    pub const TOKEN_EXPIRE: Field<Token, Option<nx_db::time::OffsetDateTime>> = Field::new("expire");
    pub const TOKEN_USER: Field<Token, Option<String>> = Field::new("user");

    fn encode_token_secret(value: Option<String>) -> Result<Option<String>, DatabaseError> {
        if let Some(value) = value {
            let value = crate::filters::encrypt(value)?;
            Ok(Some(value))
        } else {
            Ok(None)
        }
    }

    fn encode_query_token_secret(value: Option<String>) -> Result<nx_db::traits::storage::StorageValue, DatabaseError> {
        if let Some(value) = value {
            Ok(nx_db::IntoStorage::into_storage(crate::filters::encrypt(value)?))
        } else {
            Ok(nx_db::traits::storage::StorageValue::Null)
        }
    }

    fn decode_token_secret(value: Option<String>) -> Result<Option<String>, DatabaseError> {
        if let Some(value) = value {
            let value = crate::filters::decrypt(value)?;
            Ok(Some(value))
        } else {
            Ok(None)
        }
    }

    const TOKENS_ATTRIBUTES: &[AttributeSchema] = &[
        AttributeSchema {
            id: "userInternalId",
            column: "userInternalId",
            kind: AttributeKind::Integer,
            required: true,
            array: false,
            length: None,
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: None,
        },
        AttributeSchema {
            id: "userId",
            column: "userId",
            kind: AttributeKind::String,
            required: false,
            array: false,
            length: Some(255),
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: None,
        },
        AttributeSchema {
            id: "kind",
            column: "kind",
            kind: AttributeKind::Integer,
            required: true,
            array: false,
            length: None,
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: None,
        },
        AttributeSchema {
            id: "secret",
            column: "secret",
            kind: AttributeKind::String,
            required: false,
            array: false,
            length: Some(1000),
            persistence: AttributePersistence::Persisted,
            filters: &["encrypt"],
            relationship: None,
        },
        AttributeSchema {
            id: "expire",
            column: "expire",
            kind: AttributeKind::Timestamp,
            required: false,
            array: false,
            length: None,
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: None,
        },
        AttributeSchema {
            id: "user",
            column: "user",
            kind: AttributeKind::Relationship,
            required: false,
            array: false,
            length: None,
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: Some(nx_db::RelationshipSchema {
                related_collection: "users",
                kind: nx_db::RelationshipKind::ManyToOne,
                side: nx_db::RelationshipSide::Parent,
                two_way: true,
                two_way_key: Some("tokens"),
                on_delete: nx_db::OnDeleteAction::Cascade,
            }),
        },
    ];
    const TOKENS_INDEXES: &[nx_db::IndexSchema] = &[
    ];
    pub static TOKENS_SCHEMA: CollectionSchema = CollectionSchema { id: "tokens", name: "Tokens", document_security: true, enabled: true, permissions: &["create(\"any\")"], attributes: TOKENS_ATTRIBUTES, indexes: TOKENS_INDEXES };
    impl Token {
        pub const ID: Field<Token, TokenId> = Field::new(FIELD_ID);
        pub const USER_INTERNAL_ID: Field<Token, i64> = Field::new("userInternalId");
        pub const USER_ID: Field<Token, Option<String>> = Field::new("userId");
        pub const KIND: Field<Token, i64> = Field::new("kind");
        pub const SECRET: EncodedField<Token, Option<String>> = EncodedField::new("secret", encode_query_token_secret);
        pub const EXPIRE: Field<Token, Option<nx_db::time::OffsetDateTime>> = Field::new("expire");
        pub const USER: Field<Token, Option<String>> = Field::new("user");
    }
    nx_db::impl_model! { name: Token, id: TokenId, entity: TokenEntity, create: CreateToken, update: UpdateToken, schema: TOKENS_SCHEMA, fields: {                 "userInternalId" => user_internal_id : i64 :required,                 "userId" => user_id : Option<String>,                 "kind" => kind : i64 :required,                 "secret" => secret : Option<String> [encode_token_secret, decode_token_secret],                 "expire" => expire : Option<nx_db::time::OffsetDateTime>,                 "user" => user : Option<String> } }
    pub type AuthenticatorId = Key<255>;

    #[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
    pub struct AuthenticatorEntity {
        pub id: AuthenticatorId,
        pub user_internal_id: Option<i64>,
        pub kind: Option<String>,
        pub verified: Option<bool>,
        pub user: Option<String>,
        pub _metadata: nx_db::Metadata,
    }

    #[derive(Debug, Clone)]
    pub struct CreateAuthenticator {
        pub id: AuthenticatorId,
        pub user_internal_id: Option<i64>,
        pub kind: Option<String>,
        pub verified: Option<bool>,
        pub user: Option<String>,
        pub permissions: Vec<String>,
    }

    #[derive(Debug, Clone, Default)]
    pub struct UpdateAuthenticator {
        pub user_internal_id: Patch<Option<i64>>,
        pub kind: Patch<Option<String>>,
        pub verified: Patch<Option<bool>>,
        pub user: Patch<Option<String>>,
        pub permissions: Patch<Vec<String>>,
    }

    #[derive(Debug, Clone, Copy)]
    pub struct Authenticator;
    pub const AUTHENTICATOR: Authenticator = Authenticator;

    pub const AUTHENTICATOR_ID: Field<Authenticator, AuthenticatorId> = Field::new(FIELD_ID);
    pub const AUTHENTICATOR_USER_INTERNAL_ID: Field<Authenticator, Option<i64>> = Field::new("userInternalId");
    pub const AUTHENTICATOR_KIND: Field<Authenticator, Option<String>> = Field::new("kind");
    pub const AUTHENTICATOR_VERIFIED: Field<Authenticator, Option<bool>> = Field::new("verified");
    pub const AUTHENTICATOR_USER: Field<Authenticator, Option<String>> = Field::new("user");

    const AUTHENTICATORS_ATTRIBUTES: &[AttributeSchema] = &[
        AttributeSchema {
            id: "userInternalId",
            column: "userInternalId",
            kind: AttributeKind::Integer,
            required: false,
            array: false,
            length: None,
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: None,
        },
        AttributeSchema {
            id: "kind",
            column: "kind",
            kind: AttributeKind::String,
            required: false,
            array: false,
            length: Some(255),
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: None,
        },
        AttributeSchema {
            id: "verified",
            column: "verified",
            kind: AttributeKind::Boolean,
            required: false,
            array: false,
            length: None,
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: None,
        },
        AttributeSchema {
            id: "user",
            column: "user",
            kind: AttributeKind::Relationship,
            required: false,
            array: false,
            length: None,
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: Some(nx_db::RelationshipSchema {
                related_collection: "users",
                kind: nx_db::RelationshipKind::ManyToOne,
                side: nx_db::RelationshipSide::Parent,
                two_way: true,
                two_way_key: Some("authenticators"),
                on_delete: nx_db::OnDeleteAction::Restrict,
            }),
        },
    ];
    const AUTHENTICATORS_INDEXES: &[nx_db::IndexSchema] = &[
    ];
    pub static AUTHENTICATORS_SCHEMA: CollectionSchema = CollectionSchema { id: "authenticators", name: "Authenticators", document_security: true, enabled: true, permissions: &["create(\"any\")"], attributes: AUTHENTICATORS_ATTRIBUTES, indexes: AUTHENTICATORS_INDEXES };
    impl Authenticator {
        pub const ID: Field<Authenticator, AuthenticatorId> = Field::new(FIELD_ID);
        pub const USER_INTERNAL_ID: Field<Authenticator, Option<i64>> = Field::new("userInternalId");
        pub const KIND: Field<Authenticator, Option<String>> = Field::new("kind");
        pub const VERIFIED: Field<Authenticator, Option<bool>> = Field::new("verified");
        pub const USER: Field<Authenticator, Option<String>> = Field::new("user");
    }
    nx_db::impl_model! { name: Authenticator, id: AuthenticatorId, entity: AuthenticatorEntity, create: CreateAuthenticator, update: UpdateAuthenticator, schema: AUTHENTICATORS_SCHEMA, fields: {                 "userInternalId" => user_internal_id : Option<i64>,                 "kind" => kind : Option<String>,                 "verified" => verified : Option<bool>,                 "user" => user : Option<String> } }
    pub type ChallengeId = Key<255>;

    #[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
    pub struct ChallengeEntity {
        pub id: ChallengeId,
        pub user_internal_id: Option<i64>,
        pub kind: Option<String>,
        pub expire: Option<nx_db::time::OffsetDateTime>,
        pub user: Option<String>,
        pub _metadata: nx_db::Metadata,
    }

    #[derive(Debug, Clone)]
    pub struct CreateChallenge {
        pub id: ChallengeId,
        pub user_internal_id: Option<i64>,
        pub kind: Option<String>,
        pub expire: Option<nx_db::time::OffsetDateTime>,
        pub user: Option<String>,
        pub permissions: Vec<String>,
    }

    #[derive(Debug, Clone, Default)]
    pub struct UpdateChallenge {
        pub user_internal_id: Patch<Option<i64>>,
        pub kind: Patch<Option<String>>,
        pub expire: Patch<Option<nx_db::time::OffsetDateTime>>,
        pub user: Patch<Option<String>>,
        pub permissions: Patch<Vec<String>>,
    }

    #[derive(Debug, Clone, Copy)]
    pub struct Challenge;
    pub const CHALLENGE: Challenge = Challenge;

    pub const CHALLENGE_ID: Field<Challenge, ChallengeId> = Field::new(FIELD_ID);
    pub const CHALLENGE_USER_INTERNAL_ID: Field<Challenge, Option<i64>> = Field::new("userInternalId");
    pub const CHALLENGE_KIND: Field<Challenge, Option<String>> = Field::new("kind");
    pub const CHALLENGE_EXPIRE: Field<Challenge, Option<nx_db::time::OffsetDateTime>> = Field::new("expire");
    pub const CHALLENGE_USER: Field<Challenge, Option<String>> = Field::new("user");

    const CHALLENGES_ATTRIBUTES: &[AttributeSchema] = &[
        AttributeSchema {
            id: "userInternalId",
            column: "userInternalId",
            kind: AttributeKind::Integer,
            required: false,
            array: false,
            length: None,
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: None,
        },
        AttributeSchema {
            id: "kind",
            column: "kind",
            kind: AttributeKind::String,
            required: false,
            array: false,
            length: Some(255),
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: None,
        },
        AttributeSchema {
            id: "expire",
            column: "expire",
            kind: AttributeKind::Timestamp,
            required: false,
            array: false,
            length: None,
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: None,
        },
        AttributeSchema {
            id: "user",
            column: "user",
            kind: AttributeKind::Relationship,
            required: false,
            array: false,
            length: None,
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: Some(nx_db::RelationshipSchema {
                related_collection: "users",
                kind: nx_db::RelationshipKind::ManyToOne,
                side: nx_db::RelationshipSide::Parent,
                two_way: true,
                two_way_key: Some("challenges"),
                on_delete: nx_db::OnDeleteAction::Restrict,
            }),
        },
    ];
    const CHALLENGES_INDEXES: &[nx_db::IndexSchema] = &[
    ];
    pub static CHALLENGES_SCHEMA: CollectionSchema = CollectionSchema { id: "challenges", name: "Challenges", document_security: true, enabled: true, permissions: &["create(\"any\")"], attributes: CHALLENGES_ATTRIBUTES, indexes: CHALLENGES_INDEXES };
    impl Challenge {
        pub const ID: Field<Challenge, ChallengeId> = Field::new(FIELD_ID);
        pub const USER_INTERNAL_ID: Field<Challenge, Option<i64>> = Field::new("userInternalId");
        pub const KIND: Field<Challenge, Option<String>> = Field::new("kind");
        pub const EXPIRE: Field<Challenge, Option<nx_db::time::OffsetDateTime>> = Field::new("expire");
        pub const USER: Field<Challenge, Option<String>> = Field::new("user");
    }
    nx_db::impl_model! { name: Challenge, id: ChallengeId, entity: ChallengeEntity, create: CreateChallenge, update: UpdateChallenge, schema: CHALLENGES_SCHEMA, fields: {                 "userInternalId" => user_internal_id : Option<i64>,                 "kind" => kind : Option<String>,                 "expire" => expire : Option<nx_db::time::OffsetDateTime>,                 "user" => user : Option<String> } }
    pub type IdentityId = Key<255>;

    #[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
    pub struct IdentityEntity {
        pub id: IdentityId,
        pub user_internal_id: Option<i64>,
        pub provider: Option<String>,
        pub provider_uid: Option<String>,
        pub provider_email: Option<String>,
        pub user: Option<String>,
        pub _metadata: nx_db::Metadata,
    }

    #[derive(Debug, Clone)]
    pub struct CreateIdentity {
        pub id: IdentityId,
        pub user_internal_id: Option<i64>,
        pub provider: Option<String>,
        pub provider_uid: Option<String>,
        pub provider_email: Option<String>,
        pub user: Option<String>,
        pub permissions: Vec<String>,
    }

    #[derive(Debug, Clone, Default)]
    pub struct UpdateIdentity {
        pub user_internal_id: Patch<Option<i64>>,
        pub provider: Patch<Option<String>>,
        pub provider_uid: Patch<Option<String>>,
        pub provider_email: Patch<Option<String>>,
        pub user: Patch<Option<String>>,
        pub permissions: Patch<Vec<String>>,
    }

    #[derive(Debug, Clone, Copy)]
    pub struct Identity;
    pub const IDENTITY: Identity = Identity;

    pub const IDENTITY_ID: Field<Identity, IdentityId> = Field::new(FIELD_ID);
    pub const IDENTITY_USER_INTERNAL_ID: Field<Identity, Option<i64>> = Field::new("userInternalId");
    pub const IDENTITY_PROVIDER: Field<Identity, Option<String>> = Field::new("provider");
    pub const IDENTITY_PROVIDER_UID: Field<Identity, Option<String>> = Field::new("providerUid");
    pub const IDENTITY_PROVIDER_EMAIL: Field<Identity, Option<String>> = Field::new("providerEmail");
    pub const IDENTITY_USER: Field<Identity, Option<String>> = Field::new("user");

    const IDENTITIES_ATTRIBUTES: &[AttributeSchema] = &[
        AttributeSchema {
            id: "userInternalId",
            column: "userInternalId",
            kind: AttributeKind::Integer,
            required: false,
            array: false,
            length: None,
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: None,
        },
        AttributeSchema {
            id: "provider",
            column: "provider",
            kind: AttributeKind::String,
            required: false,
            array: false,
            length: Some(128),
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: None,
        },
        AttributeSchema {
            id: "providerUid",
            column: "providerUid",
            kind: AttributeKind::String,
            required: false,
            array: false,
            length: Some(2048),
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: None,
        },
        AttributeSchema {
            id: "providerEmail",
            column: "providerEmail",
            kind: AttributeKind::String,
            required: false,
            array: false,
            length: Some(320),
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: None,
        },
        AttributeSchema {
            id: "user",
            column: "user",
            kind: AttributeKind::Relationship,
            required: false,
            array: false,
            length: None,
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: Some(nx_db::RelationshipSchema {
                related_collection: "users",
                kind: nx_db::RelationshipKind::ManyToOne,
                side: nx_db::RelationshipSide::Parent,
                two_way: true,
                two_way_key: Some("identities"),
                on_delete: nx_db::OnDeleteAction::Restrict,
            }),
        },
    ];
    const IDENTITIES_INDEXES: &[nx_db::IndexSchema] = &[
    ];
    pub static IDENTITIES_SCHEMA: CollectionSchema = CollectionSchema { id: "identities", name: "Identities", document_security: true, enabled: true, permissions: &["create(\"any\")"], attributes: IDENTITIES_ATTRIBUTES, indexes: IDENTITIES_INDEXES };
    impl Identity {
        pub const ID: Field<Identity, IdentityId> = Field::new(FIELD_ID);
        pub const USER_INTERNAL_ID: Field<Identity, Option<i64>> = Field::new("userInternalId");
        pub const PROVIDER: Field<Identity, Option<String>> = Field::new("provider");
        pub const PROVIDER_UID: Field<Identity, Option<String>> = Field::new("providerUid");
        pub const PROVIDER_EMAIL: Field<Identity, Option<String>> = Field::new("providerEmail");
        pub const USER: Field<Identity, Option<String>> = Field::new("user");
    }
    nx_db::impl_model! { name: Identity, id: IdentityId, entity: IdentityEntity, create: CreateIdentity, update: UpdateIdentity, schema: IDENTITIES_SCHEMA, fields: {                 "userInternalId" => user_internal_id : Option<i64>,                 "provider" => provider : Option<String>,                 "providerUid" => provider_uid : Option<String>,                 "providerEmail" => provider_email : Option<String>,                 "user" => user : Option<String> } }
    pub type MembershipId = Key<255>;

    #[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
    pub struct MembershipEntity {
        pub id: MembershipId,
        pub user_internal_id: i64,
        pub team_internal_id: i64,
        pub roles: Option<Vec<String>>,
        pub invited: Option<nx_db::time::OffsetDateTime>,
        pub joined: Option<nx_db::time::OffsetDateTime>,
        pub confirm: Option<bool>,
        pub user: Option<String>,
        pub team: Option<String>,
        pub _metadata: nx_db::Metadata,
    }

    #[derive(Debug, Clone)]
    pub struct CreateMembership {
        pub id: MembershipId,
        pub user_internal_id: i64,
        pub team_internal_id: i64,
        pub roles: Option<Vec<String>>,
        pub invited: Option<nx_db::time::OffsetDateTime>,
        pub joined: Option<nx_db::time::OffsetDateTime>,
        pub confirm: Option<bool>,
        pub user: Option<String>,
        pub team: Option<String>,
        pub permissions: Vec<String>,
    }

    #[derive(Debug, Clone, Default)]
    pub struct UpdateMembership {
        pub user_internal_id: Patch<i64>,
        pub team_internal_id: Patch<i64>,
        pub roles: Patch<Option<Vec<String>>>,
        pub invited: Patch<Option<nx_db::time::OffsetDateTime>>,
        pub joined: Patch<Option<nx_db::time::OffsetDateTime>>,
        pub confirm: Patch<Option<bool>>,
        pub user: Patch<Option<String>>,
        pub team: Patch<Option<String>>,
        pub permissions: Patch<Vec<String>>,
    }

    #[derive(Debug, Clone, Copy)]
    pub struct Membership;
    pub const MEMBERSHIP: Membership = Membership;

    pub const MEMBERSHIP_ID: Field<Membership, MembershipId> = Field::new(FIELD_ID);
    pub const MEMBERSHIP_USER_INTERNAL_ID: Field<Membership, i64> = Field::new("userInternalId");
    pub const MEMBERSHIP_TEAM_INTERNAL_ID: Field<Membership, i64> = Field::new("teamInternalId");
    pub const MEMBERSHIP_ROLES: Field<Membership, Option<Vec<String>>> = Field::new("roles");
    pub const MEMBERSHIP_INVITED: Field<Membership, Option<nx_db::time::OffsetDateTime>> = Field::new("invited");
    pub const MEMBERSHIP_JOINED: Field<Membership, Option<nx_db::time::OffsetDateTime>> = Field::new("joined");
    pub const MEMBERSHIP_CONFIRM: Field<Membership, Option<bool>> = Field::new("confirm");
    pub const MEMBERSHIP_USER: Field<Membership, Option<String>> = Field::new("user");
    pub const MEMBERSHIP_TEAM: Field<Membership, Option<String>> = Field::new("team");

    const MEMBERSHIPS_ATTRIBUTES: &[AttributeSchema] = &[
        AttributeSchema {
            id: "userInternalId",
            column: "userInternalId",
            kind: AttributeKind::Integer,
            required: true,
            array: false,
            length: None,
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: None,
        },
        AttributeSchema {
            id: "teamInternalId",
            column: "teamInternalId",
            kind: AttributeKind::Integer,
            required: true,
            array: false,
            length: None,
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: None,
        },
        AttributeSchema {
            id: "roles",
            column: "roles",
            kind: AttributeKind::String,
            required: false,
            array: true,
            length: Some(128),
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: None,
        },
        AttributeSchema {
            id: "invited",
            column: "invited",
            kind: AttributeKind::Timestamp,
            required: false,
            array: false,
            length: None,
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: None,
        },
        AttributeSchema {
            id: "joined",
            column: "joined",
            kind: AttributeKind::Timestamp,
            required: false,
            array: false,
            length: None,
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: None,
        },
        AttributeSchema {
            id: "confirm",
            column: "confirm",
            kind: AttributeKind::Boolean,
            required: false,
            array: false,
            length: None,
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: None,
        },
        AttributeSchema {
            id: "user",
            column: "user",
            kind: AttributeKind::Relationship,
            required: false,
            array: false,
            length: None,
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: Some(nx_db::RelationshipSchema {
                related_collection: "users",
                kind: nx_db::RelationshipKind::ManyToOne,
                side: nx_db::RelationshipSide::Parent,
                two_way: true,
                two_way_key: Some("memberships"),
                on_delete: nx_db::OnDeleteAction::Cascade,
            }),
        },
        AttributeSchema {
            id: "team",
            column: "team",
            kind: AttributeKind::Relationship,
            required: false,
            array: false,
            length: None,
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: Some(nx_db::RelationshipSchema {
                related_collection: "teams",
                kind: nx_db::RelationshipKind::ManyToOne,
                side: nx_db::RelationshipSide::Parent,
                two_way: true,
                two_way_key: Some("memberships"),
                on_delete: nx_db::OnDeleteAction::Cascade,
            }),
        },
    ];
    const MEMBERSHIPS_INDEXES: &[nx_db::IndexSchema] = &[
    ];
    pub static MEMBERSHIPS_SCHEMA: CollectionSchema = CollectionSchema { id: "memberships", name: "Memberships", document_security: true, enabled: true, permissions: &["create(\"any\")"], attributes: MEMBERSHIPS_ATTRIBUTES, indexes: MEMBERSHIPS_INDEXES };
    impl Membership {
        pub const ID: Field<Membership, MembershipId> = Field::new(FIELD_ID);
        pub const USER_INTERNAL_ID: Field<Membership, i64> = Field::new("userInternalId");
        pub const TEAM_INTERNAL_ID: Field<Membership, i64> = Field::new("teamInternalId");
        pub const ROLES: Field<Membership, Option<Vec<String>>> = Field::new("roles");
        pub const INVITED: Field<Membership, Option<nx_db::time::OffsetDateTime>> = Field::new("invited");
        pub const JOINED: Field<Membership, Option<nx_db::time::OffsetDateTime>> = Field::new("joined");
        pub const CONFIRM: Field<Membership, Option<bool>> = Field::new("confirm");
        pub const USER: Field<Membership, Option<String>> = Field::new("user");
        pub const TEAM: Field<Membership, Option<String>> = Field::new("team");
    }
    nx_db::impl_model! { name: Membership, id: MembershipId, entity: MembershipEntity, create: CreateMembership, update: UpdateMembership, schema: MEMBERSHIPS_SCHEMA, fields: {                 "userInternalId" => user_internal_id : i64 :required,                 "teamInternalId" => team_internal_id : i64 :required,                 "roles" => roles : Option<Vec<String>>,                 "invited" => invited : Option<nx_db::time::OffsetDateTime>,                 "joined" => joined : Option<nx_db::time::OffsetDateTime>,                 "confirm" => confirm : Option<bool>,                 "user" => user : Option<String>,                 "team" => team : Option<String> } }
    pub type TargetId = Key<255>;

    #[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
    pub struct TargetEntity {
        pub id: TargetId,
        pub user_internal_id: i64,
        pub provider_type: String,
        pub identifier: String,
        pub expired: Option<bool>,
        pub user: Option<String>,
        pub _metadata: nx_db::Metadata,
    }

    #[derive(Debug, Clone)]
    pub struct CreateTarget {
        pub id: TargetId,
        pub user_internal_id: i64,
        pub provider_type: String,
        pub identifier: String,
        pub expired: Option<bool>,
        pub user: Option<String>,
        pub permissions: Vec<String>,
    }

    #[derive(Debug, Clone, Default)]
    pub struct UpdateTarget {
        pub user_internal_id: Patch<i64>,
        pub provider_type: Patch<String>,
        pub identifier: Patch<String>,
        pub expired: Patch<Option<bool>>,
        pub user: Patch<Option<String>>,
        pub permissions: Patch<Vec<String>>,
    }

    #[derive(Debug, Clone, Copy)]
    pub struct Target;
    pub const TARGET: Target = Target;

    pub const TARGET_ID: Field<Target, TargetId> = Field::new(FIELD_ID);
    pub const TARGET_USER_INTERNAL_ID: Field<Target, i64> = Field::new("userInternalId");
    pub const TARGET_PROVIDER_TYPE: Field<Target, String> = Field::new("providerType");
    pub const TARGET_IDENTIFIER: Field<Target, String> = Field::new("identifier");
    pub const TARGET_EXPIRED: Field<Target, Option<bool>> = Field::new("expired");
    pub const TARGET_USER: Field<Target, Option<String>> = Field::new("user");

    const TARGETS_ATTRIBUTES: &[AttributeSchema] = &[
        AttributeSchema {
            id: "userInternalId",
            column: "userInternalId",
            kind: AttributeKind::Integer,
            required: true,
            array: false,
            length: None,
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: None,
        },
        AttributeSchema {
            id: "providerType",
            column: "providerType",
            kind: AttributeKind::String,
            required: true,
            array: false,
            length: Some(255),
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: None,
        },
        AttributeSchema {
            id: "identifier",
            column: "identifier",
            kind: AttributeKind::String,
            required: true,
            array: false,
            length: Some(255),
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: None,
        },
        AttributeSchema {
            id: "expired",
            column: "expired",
            kind: AttributeKind::Boolean,
            required: false,
            array: false,
            length: None,
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: None,
        },
        AttributeSchema {
            id: "user",
            column: "user",
            kind: AttributeKind::Relationship,
            required: false,
            array: false,
            length: None,
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: Some(nx_db::RelationshipSchema {
                related_collection: "users",
                kind: nx_db::RelationshipKind::ManyToOne,
                side: nx_db::RelationshipSide::Parent,
                two_way: true,
                two_way_key: Some("targets"),
                on_delete: nx_db::OnDeleteAction::Cascade,
            }),
        },
    ];
    const TARGETS_INDEXES: &[nx_db::IndexSchema] = &[
    ];
    pub static TARGETS_SCHEMA: CollectionSchema = CollectionSchema { id: "targets", name: "Targets", document_security: true, enabled: true, permissions: &["create(\"any\")"], attributes: TARGETS_ATTRIBUTES, indexes: TARGETS_INDEXES };
    impl Target {
        pub const ID: Field<Target, TargetId> = Field::new(FIELD_ID);
        pub const USER_INTERNAL_ID: Field<Target, i64> = Field::new("userInternalId");
        pub const PROVIDER_TYPE: Field<Target, String> = Field::new("providerType");
        pub const IDENTIFIER: Field<Target, String> = Field::new("identifier");
        pub const EXPIRED: Field<Target, Option<bool>> = Field::new("expired");
        pub const USER: Field<Target, Option<String>> = Field::new("user");
    }
    nx_db::impl_model! { name: Target, id: TargetId, entity: TargetEntity, create: CreateTarget, update: UpdateTarget, schema: TARGETS_SCHEMA, fields: {                 "userInternalId" => user_internal_id : i64 :required,                 "providerType" => provider_type : String :required,                 "identifier" => identifier : String :required,                 "expired" => expired : Option<bool>,                 "user" => user : Option<String> } }
    pub fn registry() -> Result<StaticRegistry, DatabaseError> {
        let registry = StaticRegistry::new()
            .register(&USERS_SCHEMA)?
            .register(&TEAMS_SCHEMA)?
            .register(&SESSIONS_SCHEMA)?
            .register(&TOKENS_SCHEMA)?
            .register(&AUTHENTICATORS_SCHEMA)?
            .register(&CHALLENGES_SCHEMA)?
            .register(&IDENTITIES_SCHEMA)?
            .register(&MEMBERSHIPS_SCHEMA)?
            .register(&TARGETS_SCHEMA)?
            ;
        Ok(registry)
    }
}
