// @generated by database-cli.
// Do not edit by hand.

#[allow(dead_code)]
#[allow(unused_imports)]
pub mod filtered_app_models {
    use nx_db::traits::storage::StorageRecord;
    use nx_db::{insert_value, take_optional, take_required, get_optional, get_required, AttributeKind, AttributePersistence, AttributeSchema, CollectionSchema, Context, DatabaseError, EncodedField, Field, Key, Model, Patch, QuerySpec, RelationshipKind, RelationshipSchema, RelationshipSide, StaticRegistry, FIELD_ID, FIELD_SEQUENCE, FIELD_CREATED_AT, FIELD_UPDATED_AT, FIELD_PERMISSIONS};

    pub type UserId = Key<32>;

    #[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
    pub struct UserEntity {
        pub id: UserId,
        pub name: crate::DisplayName,
        pub active: bool,
        pub _metadata: nx_db::Metadata,
    }

    #[derive(Debug, Clone)]
    pub struct CreateUser {
        pub id: UserId,
        pub name: crate::DisplayName,
        pub active: bool,
        pub permissions: Vec<String>,
    }

    #[derive(Debug, Clone, Default)]
    pub struct UpdateUser {
        pub name: Patch<crate::DisplayName>,
        pub active: Patch<bool>,
        pub permissions: Patch<Vec<String>>,
    }

    #[derive(Debug, Clone, Copy)]
    pub struct User;
    pub const USER: User = User;

    pub const USER_ID: Field<User, UserId> = Field::new(FIELD_ID);
    pub const USER_NAME: EncodedField<User, crate::DisplayName> = EncodedField::new("name", encode_query_user_name);
    pub const USER_ACTIVE: Field<User, bool> = Field::new("active");

    fn encode_user_name(value: crate::DisplayName) -> Result<String, DatabaseError> {
        let value = crate::codecs::encode_display_name(value)?;
        Ok(value)
    }

    fn encode_query_user_name(value: crate::DisplayName) -> Result<nx_db::traits::storage::StorageValue, DatabaseError> {
        Ok(nx_db::IntoStorage::into_storage(encode_user_name(value)?))
    }

    fn decode_user_name(value: String) -> Result<crate::DisplayName, DatabaseError> {
        let value = crate::codecs::decode_display_name(value)?;
        Ok(value)
    }

    const USERS_ATTRIBUTES: &[AttributeSchema] = &[
        AttributeSchema {
            id: "name",
            column: "name",
            kind: AttributeKind::String,
            required: true,
            array: false,
            length: None,
            persistence: AttributePersistence::Persisted,
            filters: &["displayName"],
            relationship: None,
        },
        AttributeSchema {
            id: "active",
            column: "active",
            kind: AttributeKind::Boolean,
            required: true,
            array: false,
            length: None,
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: None,
        },
    ];
    const USERS_INDEXES: &[nx_db::IndexSchema] = &[
    ];
    pub static USERS_SCHEMA: CollectionSchema = CollectionSchema { id: "users", name: "Users", document_security: true, enabled: true, permissions: &["read(\"any\")", "create(\"any\")", "update(\"any\")", "delete(\"any\")"], attributes: USERS_ATTRIBUTES, indexes: USERS_INDEXES };
    impl User {
        pub const ID: Field<User, UserId> = Field::new(FIELD_ID);
        pub const NAME: EncodedField<User, crate::DisplayName> = EncodedField::new("name", encode_query_user_name);
        pub const ACTIVE: Field<User, bool> = Field::new("active");
    }
    nx_db::impl_model! { name: User, id: UserId, entity: UserEntity, create: CreateUser, update: UpdateUser, schema: USERS_SCHEMA, fields: {                 "name" => name : String [encode_user_name, decode_user_name] :required,                 "active" => active : bool :required } }
    pub fn registry() -> Result<StaticRegistry, DatabaseError> {
        let registry = StaticRegistry::new()
            .register(&USERS_SCHEMA)?
            ;
        Ok(registry)
    }
}
