// @generated by database-cli.
// Do not edit by hand.

pub mod filtered_app_models {
    use database::traits::storage::StorageRecord;
    use database::{insert_value, take_required, AttributeKind, AttributePersistence, AttributeSchema, CollectionSchema, Context, DatabaseError, EncodedField, Field, Key, Model, Patch, StaticRegistry};

    pub type UserId = Key<32>;

    #[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
    pub struct UserEntity {
        pub id: UserId,
        pub name: crate::DisplayName,
        pub active: bool,
    }

    #[derive(Debug, Clone)]
    pub struct CreateUser {
        pub id: UserId,
        pub name: crate::DisplayName,
        pub active: bool,
    }

    #[derive(Debug, Clone, Default)]
    pub struct UpdateUser {
        pub name: Patch<crate::DisplayName>,
        pub active: Patch<bool>,
    }

    #[derive(Debug, Clone, Copy)]
    pub struct User;
    pub const USER: User = User;

    pub const USER_ID: Field<User, UserId> = Field::new(database::FIELD_ID);
    pub const USER_NAME: EncodedField<User, crate::DisplayName> = EncodedField::new("name", encode_query_user_name);
    pub const USER_ACTIVE: Field<User, bool> = Field::new("active");

    fn encode_user_name(value: crate::DisplayName) -> Result<String, DatabaseError> {
        let value = crate::codecs::encode_display_name(value)?;
        Ok(value)
    }

    fn encode_query_user_name(value: crate::DisplayName) -> Result<database::traits::storage::StorageValue, DatabaseError> {
        Ok(database::IntoStorage::into_storage(encode_user_name(value)?))
    }

    fn decode_user_name(value: String) -> Result<crate::DisplayName, DatabaseError> {
        let value = crate::codecs::decode_display_name(value)?;
        Ok(value)
    }

    const USERS_ATTRIBUTES: &[AttributeSchema] = &[
        AttributeSchema {
            id: "name",
            column: "name",
            kind: AttributeKind::String,
            required: true,
            array: false,
            persistence: AttributePersistence::Persisted,
            filters: &["displayName"],
            relationship: None,
        },
        AttributeSchema {
            id: "active",
            column: "active",
            kind: AttributeKind::Boolean,
            required: true,
            array: false,
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: None,
        },
    ];

    const USERS_INDEXES: &[database::IndexSchema] = &[
    ];

    pub static USERS_SCHEMA: CollectionSchema = CollectionSchema {
        id: "users",
        name: "Users",
        document_security: true,
        enabled: true,
        permissions: &["read(\"any\")", "create(\"any\")", "update(\"any\")", "delete(\"any\")"],
        attributes: USERS_ATTRIBUTES,
        indexes: USERS_INDEXES,
    };

    impl Model for User {
        type Id = UserId;
        type Entity = UserEntity;
        type Create = CreateUser;
        type Update = UpdateUser;

        fn schema() -> &'static CollectionSchema {
            &USERS_SCHEMA
        }

        fn entity_to_id(entity: &Self::Entity) -> &Self::Id {
            &entity.id
        }

        fn create_to_record(input: Self::Create, _context: &Context) -> Result<StorageRecord, DatabaseError> {
            let mut record = StorageRecord::new();
            insert_value(&mut record, database::FIELD_ID, input.id);
            insert_value(&mut record, "name", encode_user_name(input.name)?);
            insert_value(&mut record, "active", input.active);
            Ok(record)
        }

        fn update_to_record(input: Self::Update, _context: &Context) -> Result<StorageRecord, DatabaseError> {
            let mut record = StorageRecord::new();
            if let Patch::Set(value) = input.name { insert_value(&mut record, "name", encode_user_name(value)?); }
            if let Patch::Set(value) = input.active { insert_value(&mut record, "active", value); }
            Ok(record)
        }

        fn entity_from_record(mut record: StorageRecord, _context: &Context) -> Result<Self::Entity, DatabaseError> {
            Ok(UserEntity {
                id: take_required(&mut record, database::FIELD_ID)?,
                name: decode_user_name(take_required::<String>(&mut record, "name")?)?,
                active: take_required(&mut record, "active")?,
            })
        }
    }

    pub fn registry() -> Result<StaticRegistry, DatabaseError> {
        let registry = StaticRegistry::new()
            .register(&USERS_SCHEMA)?
            ;
        Ok(registry)
    }
}
