// @generated by database-cli.
// Do not edit by hand.

#[allow(dead_code)]
#[allow(unused_imports)]
pub mod app_models {
    use nx_db::traits::storage::StorageRecord;
    use nx_db::{insert_value, take_optional, take_required, get_optional, get_required, AttributeKind, AttributePersistence, AttributeSchema, CollectionSchema, Context, DatabaseError, Field, Key, Model, Patch, QuerySpec, RelationshipKind, RelationshipSchema, RelationshipSide, StaticRegistry, FIELD_ID, FIELD_SEQUENCE, FIELD_CREATED_AT, FIELD_UPDATED_AT, FIELD_PERMISSIONS};

    pub type UserId = Key<48>;

    #[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
    pub struct UserEntity {
        pub id: UserId,
        pub name: String,
        pub email: Option<String>,
        pub active: bool,
        pub _metadata: nx_db::Metadata,
    }

    #[derive(Debug, Clone)]
    pub struct CreateUser {
        pub id: Option<UserId>,
        pub name: String,
        pub email: Option<String>,
        pub active: bool,
        pub permissions: Vec<String>,
    }

    nx_db::impl_create_builder! { create: CreateUser, id: UserId, required: { name: String, active: bool }, optional: { email: Option<String> } }

    #[derive(Debug, Clone, Default)]
    pub struct UpdateUser {
        pub name: Patch<String>,
        pub email: Patch<Option<String>>,
        pub active: Patch<bool>,
        pub permissions: Patch<Vec<String>>,
    }

    #[derive(Debug, Clone, Copy)]
    pub struct User;
    pub const USER: User = User;

    pub const USER_ID: Field<User, UserId> = Field::new(FIELD_ID);
    pub const USER_NAME: Field<User, String> = Field::new("name");
    pub const USER_EMAIL: Field<User, Option<String>> = Field::new("email");
    pub const USER_ACTIVE: Field<User, bool> = Field::new("active");

    const USERS_ATTRIBUTES: &[AttributeSchema] = &[
        AttributeSchema {
            id: "name",
            column: "name",
            kind: AttributeKind::String,
            required: true,
            array: false,
            length: None,
            default: None,
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: None,
        },
        AttributeSchema {
            id: "email",
            column: "email",
            kind: AttributeKind::String,
            required: false,
            array: false,
            length: None,
            default: None,
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: None,
        },
        AttributeSchema {
            id: "active",
            column: "active",
            kind: AttributeKind::Boolean,
            required: true,
            array: false,
            length: None,
            default: None,
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: None,
        },
    ];
    const USERS_INDEXES: &[nx_db::IndexSchema] = &[
        nx_db::IndexSchema {
            id: "users_email_unique",
            kind: nx_db::IndexKind::Unique,
            attributes: &["email"],
            orders: &[],
        },
        nx_db::IndexSchema {
            id: "users_name_active_idx",
            kind: nx_db::IndexKind::Key,
            attributes: &["name", "active"],
            orders: &[nx_db::Order::Asc, nx_db::Order::Desc],
        },
    ];
    pub static USERS_SCHEMA: CollectionSchema = CollectionSchema { id: "users", name: "Users", document_security: true, enabled: true, permissions: &["read(\"any\")", "create(\"any\")", "update(\"any\")", "delete(\"any\")"], attributes: USERS_ATTRIBUTES, indexes: USERS_INDEXES };
    impl User {
        pub const ID: Field<User, UserId> = Field::new(FIELD_ID);
        pub const NAME: Field<User, String> = Field::new("name");
        pub const EMAIL: Field<User, Option<String>> = Field::new("email");
        pub const ACTIVE: Field<User, bool> = Field::new("active");
    }
    nx_db::impl_model! { name: User, id: UserId, entity: UserEntity, create: CreateUser, update: UpdateUser, schema: USERS_SCHEMA, fields: {                 "name" => name : String :required,                 "email" => email : Option<String>,                 "active" => active : bool :required } }
    pub type SessionId = Key<48>;

    #[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
    pub struct SessionEntity {
        pub id: SessionId,
        pub user_id: String,
        pub token: String,
        pub revoked: bool,
        pub _metadata: nx_db::Metadata,
    }

    #[derive(Debug, Clone)]
    pub struct CreateSession {
        pub id: Option<SessionId>,
        pub user_id: String,
        pub token: String,
        pub revoked: bool,
        pub permissions: Vec<String>,
    }

    nx_db::impl_create_builder! { create: CreateSession, id: SessionId, required: { user_id: String, token: String, revoked: bool }, optional: {  } }

    #[derive(Debug, Clone, Default)]
    pub struct UpdateSession {
        pub user_id: Patch<String>,
        pub token: Patch<String>,
        pub revoked: Patch<bool>,
        pub permissions: Patch<Vec<String>>,
    }

    #[derive(Debug, Clone, Copy)]
    pub struct Session;
    pub const SESSION: Session = Session;

    pub const SESSION_ID: Field<Session, SessionId> = Field::new(FIELD_ID);
    pub const SESSION_USER_ID: Field<Session, String> = Field::new("userId");
    pub const SESSION_TOKEN: Field<Session, String> = Field::new("token");
    pub const SESSION_REVOKED: Field<Session, bool> = Field::new("revoked");

    const SESSIONS_ATTRIBUTES: &[AttributeSchema] = &[
        AttributeSchema {
            id: "userId",
            column: "user_id",
            kind: AttributeKind::Relationship,
            required: true,
            array: false,
            length: None,
            default: None,
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: None,
        },
        AttributeSchema {
            id: "token",
            column: "token",
            kind: AttributeKind::String,
            required: true,
            array: false,
            length: None,
            default: None,
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: None,
        },
        AttributeSchema {
            id: "revoked",
            column: "revoked",
            kind: AttributeKind::Boolean,
            required: true,
            array: false,
            length: None,
            default: None,
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: None,
        },
    ];
    const SESSIONS_INDEXES: &[nx_db::IndexSchema] = &[
        nx_db::IndexSchema {
            id: "sessions_user_token_idx",
            kind: nx_db::IndexKind::Key,
            attributes: &["userId", "token"],
            orders: &[nx_db::Order::Asc, nx_db::Order::Asc],
        },
    ];
    pub static SESSIONS_SCHEMA: CollectionSchema = CollectionSchema { id: "sessions", name: "Sessions", document_security: true, enabled: true, permissions: &["read(\"users\")", "create(\"users\")", "update(\"users\")", "delete(\"users\")"], attributes: SESSIONS_ATTRIBUTES, indexes: SESSIONS_INDEXES };
    impl Session {
        pub const ID: Field<Session, SessionId> = Field::new(FIELD_ID);
        pub const USER_ID: Field<Session, String> = Field::new("userId");
        pub const TOKEN: Field<Session, String> = Field::new("token");
        pub const REVOKED: Field<Session, bool> = Field::new("revoked");
    }
    nx_db::impl_model! { name: Session, id: SessionId, entity: SessionEntity, create: CreateSession, update: UpdateSession, schema: SESSIONS_SCHEMA, fields: {                 "userId" => user_id : String :required,                 "token" => token : String :required,                 "revoked" => revoked : bool :required } }
    pub fn registry() -> Result<StaticRegistry, DatabaseError> {
        let registry = StaticRegistry::new()
            .register(&USERS_SCHEMA)?
            .register(&SESSIONS_SCHEMA)?
            ;
        Ok(registry)
    }
}
