// @generated by database-cli.
// Do not edit by hand.

#[allow(dead_code)]
pub mod app_models {
    use nx_db::{AttributeKind, AttributeSchema, CollectionSchema, Key, Patch, FIELD_ID};

    pub type UserId = Key<48>;

    #[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize, nx_db::NxEntity)]
    #[serde(rename_all = "camelCase")]
    pub struct UserEntity {
        #[nx(id)]
        pub id: UserId,
        #[nx(field = "name", required)]
        pub name: String,
        #[nx(field = "email")]
        pub email: Option<String>,
        #[nx(field = "active", required)]
        pub active: bool,
        #[serde(flatten)]
        #[nx(metadata)]
        pub _metadata: nx_db::Metadata,
    }

    #[derive(Debug, Clone, ::serde::Serialize, ::serde::Deserialize, nx_db::NxCreate)]
    #[serde(rename_all = "camelCase")]
    pub struct CreateUser {
        #[nx(id)]
        pub id: Option<UserId>,
        #[nx(field = "name", required)]
        pub name: String,
        #[nx(field = "email")]
        pub email: Option<String>,
        #[nx(field = "active", required)]
        pub active: bool,
        #[serde(default, skip_serializing_if = "Vec::is_empty")]
        #[nx(permissions)]
        pub permissions: Vec<String>,
    }

    #[derive(Debug, Clone, Default, nx_db::NxUpdate)]
    pub struct UpdateUser {
        #[nx(field = "name")]
        pub name: Patch<String>,
        #[nx(field = "email")]
        pub email: Patch<Option<String>>,
        #[nx(field = "active")]
        pub active: Patch<bool>,
        #[nx(permissions)]
        pub permissions: Patch<Vec<String>>,
    }

    nx_db::declare_model! {
        name: User,
        const: USER,
        entity: UserEntity,
        create: CreateUser,
        update: UpdateUser,
        schema: USERS_SCHEMA,
        plain: {
            USER_ID => ID: UserId = FIELD_ID,
            USER_NAME => NAME: String = "name",
            USER_EMAIL => EMAIL: Option<String> = "email",
            USER_ACTIVE => ACTIVE: bool = "active",
        },
        encoded: {
        }
    }

    const USERS_ATTRIBUTES: &[AttributeSchema] = &[
        AttributeSchema::persisted("name", "name", AttributeKind::String).required(),
        AttributeSchema::persisted("email", "email", AttributeKind::String),
        AttributeSchema::persisted("active", "active", AttributeKind::Boolean).required(),
    ];
    const USERS_INDEXES: &[nx_db::IndexSchema] = &[
        nx_db::IndexSchema::new("users_email_unique", nx_db::IndexKind::Unique, &["email"]),
        nx_db::IndexSchema::new("users_name_active_idx", nx_db::IndexKind::Key, &["name", "active"]).orders(&[nx_db::Order::Asc, nx_db::Order::Desc]),
    ];
    pub static USERS_SCHEMA: CollectionSchema = CollectionSchema::new("users", "Users").document_security(true).permissions(&["read(\"any\")", "create(\"any\")", "update(\"any\")", "delete(\"any\")"]).attributes(USERS_ATTRIBUTES).indexes(USERS_INDEXES);
    pub type SessionId = Key<48>;

    #[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize, nx_db::NxEntity)]
    #[serde(rename_all = "camelCase")]
    pub struct SessionEntity {
        #[nx(id)]
        pub id: SessionId,
        #[nx(field = "userId", required)]
        pub user_id: String,
        #[nx(field = "token", required)]
        pub token: String,
        #[nx(field = "revoked", required)]
        pub revoked: bool,
        #[serde(flatten)]
        #[nx(metadata)]
        pub _metadata: nx_db::Metadata,
    }

    #[derive(Debug, Clone, ::serde::Serialize, ::serde::Deserialize, nx_db::NxCreate)]
    #[serde(rename_all = "camelCase")]
    pub struct CreateSession {
        #[nx(id)]
        pub id: Option<SessionId>,
        #[nx(field = "userId", required)]
        pub user_id: String,
        #[nx(field = "token", required)]
        pub token: String,
        #[nx(field = "revoked", required)]
        pub revoked: bool,
        #[serde(default, skip_serializing_if = "Vec::is_empty")]
        #[nx(permissions)]
        pub permissions: Vec<String>,
    }

    #[derive(Debug, Clone, Default, nx_db::NxUpdate)]
    pub struct UpdateSession {
        #[nx(field = "userId")]
        pub user_id: Patch<String>,
        #[nx(field = "token")]
        pub token: Patch<String>,
        #[nx(field = "revoked")]
        pub revoked: Patch<bool>,
        #[nx(permissions)]
        pub permissions: Patch<Vec<String>>,
    }

    nx_db::declare_model! {
        name: Session,
        const: SESSION,
        entity: SessionEntity,
        create: CreateSession,
        update: UpdateSession,
        schema: SESSIONS_SCHEMA,
        plain: {
            SESSION_ID => ID: SessionId = FIELD_ID,
            SESSION_USER_ID => USER_ID: String = "userId",
            SESSION_TOKEN => TOKEN: String = "token",
            SESSION_REVOKED => REVOKED: bool = "revoked",
        },
        encoded: {
        }
    }

    const SESSIONS_ATTRIBUTES: &[AttributeSchema] = &[
        AttributeSchema::persisted("userId", "user_id", AttributeKind::Relationship).required(),
        AttributeSchema::persisted("token", "token", AttributeKind::String).required(),
        AttributeSchema::persisted("revoked", "revoked", AttributeKind::Boolean).required(),
    ];
    const SESSIONS_INDEXES: &[nx_db::IndexSchema] = &[
        nx_db::IndexSchema::new("sessions_user_token_idx", nx_db::IndexKind::Key, &["userId", "token"]).orders(&[nx_db::Order::Asc, nx_db::Order::Asc]),
    ];
    pub static SESSIONS_SCHEMA: CollectionSchema = CollectionSchema::new("sessions", "Sessions").document_security(true).permissions(&["read(\"users\")", "create(\"users\")", "update(\"users\")", "delete(\"users\")"]).attributes(SESSIONS_ATTRIBUTES).indexes(SESSIONS_INDEXES);
    nx_db::impl_registry_fn! {
        fn: registry,
        schemas: [
            USERS_SCHEMA,
            SESSIONS_SCHEMA,
        ]
    }
}
