// @generated by database-cli.
// Do not edit by hand.

pub mod app_models {
    use nx_db::traits::storage::StorageRecord;
    use nx_db::{insert_value, take_optional, take_required, AttributeKind, AttributePersistence, AttributeSchema, CollectionSchema, Context, DatabaseError, Field, Key, Model, Patch, StaticRegistry};

    pub type UserId = Key<32>;

    #[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
    pub struct UserEntity {
        pub id: UserId,
        pub name: String,
        pub email: Option<String>,
        pub active: bool,
    }

    #[derive(Debug, Clone)]
    pub struct CreateUser {
        pub id: UserId,
        pub name: String,
        pub email: Option<String>,
        pub active: bool,
    }

    #[derive(Debug, Clone, Default)]
    pub struct UpdateUser {
        pub name: Patch<String>,
        pub email: Patch<Option<String>>,
        pub active: Patch<bool>,
    }

    #[derive(Debug, Clone, Copy)]
    pub struct User;
    pub const USER: User = User;

    pub const USER_ID: Field<User, UserId> = Field::new(nx_db::FIELD_ID);
    pub const USER_NAME: Field<User, String> = Field::new("name");
    pub const USER_EMAIL: Field<User, Option<String>> = Field::new("email");
    pub const USER_ACTIVE: Field<User, bool> = Field::new("active");

    const USERS_ATTRIBUTES: &[AttributeSchema] = &[
        AttributeSchema {
            id: "name",
            column: "name",
            kind: AttributeKind::String,
            required: true,
            array: false,
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: None,
        },
        AttributeSchema {
            id: "email",
            column: "email",
            kind: AttributeKind::String,
            required: false,
            array: false,
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: None,
        },
        AttributeSchema {
            id: "active",
            column: "active",
            kind: AttributeKind::Boolean,
            required: true,
            array: false,
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: None,
        },
    ];

    const USERS_INDEXES: &[nx_db::IndexSchema] = &[
        nx_db::IndexSchema {
            id: "users_email_unique",
            kind: nx_db::IndexKind::Unique,
            attributes: &["email"],
            orders: &[],
        },
        nx_db::IndexSchema {
            id: "users_name_active_idx",
            kind: nx_db::IndexKind::Key,
            attributes: &["name", "active"],
            orders: &[nx_db::Order::Asc, nx_db::Order::Desc],
        },
    ];

    pub static USERS_SCHEMA: CollectionSchema = CollectionSchema {
        id: "users",
        name: "Users",
        document_security: true,
        enabled: true,
        permissions: &["read(\"any\")", "create(\"any\")", "update(\"any\")", "delete(\"any\")"],
        attributes: USERS_ATTRIBUTES,
        indexes: USERS_INDEXES,
    };

    impl Model for User {
        type Id = UserId;
        type Entity = UserEntity;
        type Create = CreateUser;
        type Update = UpdateUser;

        fn schema() -> &'static CollectionSchema {
            &USERS_SCHEMA
        }

        fn entity_to_id(entity: &Self::Entity) -> &Self::Id {
            &entity.id
        }

        fn create_to_record(input: Self::Create, _context: &Context) -> Result<StorageRecord, DatabaseError> {
            let mut record = StorageRecord::new();
            insert_value(&mut record, nx_db::FIELD_ID, input.id);
            insert_value(&mut record, "name", input.name);
            if let Some(value) = input.email { insert_value(&mut record, "email", value); }
            insert_value(&mut record, "active", input.active);
            Ok(record)
        }

        fn update_to_record(input: Self::Update, _context: &Context) -> Result<StorageRecord, DatabaseError> {
            let mut record = StorageRecord::new();
            if let Patch::Set(value) = input.name { insert_value(&mut record, "name", value); }
            if let Patch::Set(value) = input.email { insert_value(&mut record, "email", value); }
            if let Patch::Set(value) = input.active { insert_value(&mut record, "active", value); }
            Ok(record)
        }

        fn entity_from_record(mut record: StorageRecord, _context: &Context) -> Result<Self::Entity, DatabaseError> {
            Ok(UserEntity {
                id: take_required(&mut record, nx_db::FIELD_ID)?,
                name: take_required(&mut record, "name")?,
                email: take_optional(&mut record, "email")?,
                active: take_required(&mut record, "active")?,
            })
        }
    }

    pub type SessionId = Key<48>;

    #[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
    pub struct SessionEntity {
        pub id: SessionId,
        pub user_id: String,
        pub token: String,
        pub revoked: bool,
    }

    #[derive(Debug, Clone)]
    pub struct CreateSession {
        pub id: SessionId,
        pub user_id: String,
        pub token: String,
        pub revoked: bool,
    }

    #[derive(Debug, Clone, Default)]
    pub struct UpdateSession {
        pub user_id: Patch<String>,
        pub token: Patch<String>,
        pub revoked: Patch<bool>,
    }

    #[derive(Debug, Clone, Copy)]
    pub struct Session;
    pub const SESSION: Session = Session;

    pub const SESSION_ID: Field<Session, SessionId> = Field::new(nx_db::FIELD_ID);
    pub const SESSION_USER_ID: Field<Session, String> = Field::new("userId");
    pub const SESSION_TOKEN: Field<Session, String> = Field::new("token");
    pub const SESSION_REVOKED: Field<Session, bool> = Field::new("revoked");

    const SESSIONS_ATTRIBUTES: &[AttributeSchema] = &[
        AttributeSchema {
            id: "userId",
            column: "user_id",
            kind: AttributeKind::Relationship,
            required: true,
            array: false,
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: None,
        },
        AttributeSchema {
            id: "token",
            column: "token",
            kind: AttributeKind::String,
            required: true,
            array: false,
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: None,
        },
        AttributeSchema {
            id: "revoked",
            column: "revoked",
            kind: AttributeKind::Boolean,
            required: true,
            array: false,
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: None,
        },
    ];

    const SESSIONS_INDEXES: &[nx_db::IndexSchema] = &[
        nx_db::IndexSchema {
            id: "sessions_user_token_idx",
            kind: nx_db::IndexKind::Key,
            attributes: &["userId", "token"],
            orders: &[nx_db::Order::Asc, nx_db::Order::Asc],
        },
    ];

    pub static SESSIONS_SCHEMA: CollectionSchema = CollectionSchema {
        id: "sessions",
        name: "Sessions",
        document_security: true,
        enabled: true,
        permissions: &["read(\"users\")", "create(\"users\")", "update(\"users\")", "delete(\"users\")"],
        attributes: SESSIONS_ATTRIBUTES,
        indexes: SESSIONS_INDEXES,
    };

    impl Model for Session {
        type Id = SessionId;
        type Entity = SessionEntity;
        type Create = CreateSession;
        type Update = UpdateSession;

        fn schema() -> &'static CollectionSchema {
            &SESSIONS_SCHEMA
        }

        fn entity_to_id(entity: &Self::Entity) -> &Self::Id {
            &entity.id
        }

        fn create_to_record(input: Self::Create, _context: &Context) -> Result<StorageRecord, DatabaseError> {
            let mut record = StorageRecord::new();
            insert_value(&mut record, nx_db::FIELD_ID, input.id);
            insert_value(&mut record, "userId", input.user_id);
            insert_value(&mut record, "token", input.token);
            insert_value(&mut record, "revoked", input.revoked);
            Ok(record)
        }

        fn update_to_record(input: Self::Update, _context: &Context) -> Result<StorageRecord, DatabaseError> {
            let mut record = StorageRecord::new();
            if let Patch::Set(value) = input.user_id { insert_value(&mut record, "userId", value); }
            if let Patch::Set(value) = input.token { insert_value(&mut record, "token", value); }
            if let Patch::Set(value) = input.revoked { insert_value(&mut record, "revoked", value); }
            Ok(record)
        }

        fn entity_from_record(mut record: StorageRecord, _context: &Context) -> Result<Self::Entity, DatabaseError> {
            Ok(SessionEntity {
                id: take_required(&mut record, nx_db::FIELD_ID)?,
                user_id: take_required(&mut record, "userId")?,
                token: take_required(&mut record, "token")?,
                revoked: take_required(&mut record, "revoked")?,
            })
        }
    }

    pub fn registry() -> Result<StaticRegistry, DatabaseError> {
        let registry = StaticRegistry::new()
            .register(&USERS_SCHEMA)?
            .register(&SESSIONS_SCHEMA)?
            ;
        Ok(registry)
    }
}
