// @generated by database-cli.
// Do not edit by hand.

#[allow(dead_code)]
pub mod prod_models {
    use nx_db::{AttributeKind, AttributeSchema, CollectionSchema, Key, Patch, FIELD_ID};

    pub type UserId = Key<48>;

    #[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize, nx_db::NxEntity)]
    #[serde(rename_all = "camelCase")]
    pub struct UserEntity {
        #[nx(id)]
        pub id: UserId,
        #[nx(field = "name", required)]
        pub name: String,
        #[nx(field = "email", required)]
        pub email: String,
        #[nx(field = "metadata")]
        pub metadata: Option<String>,
        #[serde(default, skip_serializing_if = "nx_db::RelationMany::is_not_loaded")]
        #[nx(loaded_many)]
        pub posts: nx_db::RelationMany<PostEntity>,
        #[serde(flatten)]
        #[nx(metadata)]
        pub _metadata: nx_db::Metadata,
    }

    #[derive(Debug, Clone, ::serde::Serialize, ::serde::Deserialize, nx_db::NxCreate)]
    #[serde(rename_all = "camelCase")]
    pub struct CreateUser {
        #[nx(id)]
        pub id: Option<UserId>,
        #[nx(field = "name", required)]
        pub name: String,
        #[nx(field = "email", required)]
        pub email: String,
        #[nx(field = "metadata")]
        pub metadata: Option<String>,
        #[serde(default, skip_serializing_if = "Vec::is_empty")]
        #[nx(permissions)]
        pub permissions: Vec<String>,
    }

    #[derive(Debug, Clone, Default, nx_db::NxUpdate)]
    pub struct UpdateUser {
        #[nx(field = "name")]
        pub name: Patch<String>,
        #[nx(field = "email")]
        pub email: Patch<String>,
        #[nx(field = "metadata")]
        pub metadata: Patch<Option<String>>,
        #[nx(permissions)]
        pub permissions: Patch<Vec<String>>,
    }

    nx_db::declare_model! {
        name: User,
        const: USER,
        entity: UserEntity,
        create: CreateUser,
        update: UpdateUser,
        schema: USERS_SCHEMA,
        plain: {
            USER_ID => ID: UserId = FIELD_ID,
            USER_NAME => NAME: String = "name",
            USER_EMAIL => EMAIL: String = "email",
            USER_METADATA => METADATA: Option<String> = "metadata",
        },
        encoded: {
        }
    }
    nx_db::impl_relation_many! { rel_const: USER_POSTS_REL, populate_const: USER_POSTS_POPULATE, rel_expr: nx_db::Rel::<User, Post>::one_to_many("posts", "author"), local_fn: populate_user_posts_local_key, remote_fn: populate_user_posts_remote_key, set_fn: populate_user_posts_set, model: User, related_model: Post, entity: UserEntity, related_entity: PostEntity, field: posts, local_key: |local_entity| local_entity.id.to_string(), remote_key: |remote_entity| Some(remote_entity.author.clone()) }

    const USERS_ATTRIBUTES: &[AttributeSchema] = &[
        AttributeSchema::persisted("name", "name", AttributeKind::String).required(),
        AttributeSchema::persisted("email", "email", AttributeKind::String).required(),
        AttributeSchema::persisted("metadata", "metadata", AttributeKind::Json),
        AttributeSchema::virtual_field("posts", AttributeKind::Relationship).relationship(nx_db::RelationshipSchema::new("posts", nx_db::RelationshipKind::OneToMany, nx_db::RelationshipSide::Parent).two_way(Some("author"))),
    ];
    const USERS_INDEXES: &[nx_db::IndexSchema] = &[
        nx_db::IndexSchema::new("users_email_unique", nx_db::IndexKind::Unique, &["email"]),
    ];
    pub static USERS_SCHEMA: CollectionSchema = CollectionSchema::new("users", "Users").document_security(true).permissions(&["read(\"any\")", "create(\"any\")"]).attributes(USERS_ATTRIBUTES).indexes(USERS_INDEXES);
    pub type PostId = Key<48>;

    #[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize, nx_db::NxEntity)]
    #[serde(rename_all = "camelCase")]
    pub struct PostEntity {
        #[nx(id)]
        pub id: PostId,
        #[nx(field = "title", required)]
        pub title: String,
        #[nx(field = "content")]
        pub content: Option<String>,
        #[nx(field = "author", required)]
        pub author: String,
        #[serde(default, skip_serializing_if = "nx_db::RelationOne::is_not_loaded")]
        #[nx(loaded_one)]
        pub author_rel: nx_db::RelationOne<UserEntity>,
        #[serde(flatten)]
        #[nx(metadata)]
        pub _metadata: nx_db::Metadata,
    }

    #[derive(Debug, Clone, ::serde::Serialize, ::serde::Deserialize, nx_db::NxCreate)]
    #[serde(rename_all = "camelCase")]
    pub struct CreatePost {
        #[nx(id)]
        pub id: Option<PostId>,
        #[nx(field = "title", required)]
        pub title: String,
        #[nx(field = "content")]
        pub content: Option<String>,
        #[nx(field = "author", required)]
        pub author: String,
        #[serde(default, skip_serializing_if = "Vec::is_empty")]
        #[nx(permissions)]
        pub permissions: Vec<String>,
    }

    #[derive(Debug, Clone, Default, nx_db::NxUpdate)]
    pub struct UpdatePost {
        #[nx(field = "title")]
        pub title: Patch<String>,
        #[nx(field = "content")]
        pub content: Patch<Option<String>>,
        #[nx(field = "author")]
        pub author: Patch<String>,
        #[nx(permissions)]
        pub permissions: Patch<Vec<String>>,
    }

    nx_db::declare_model! {
        name: Post,
        const: POST,
        entity: PostEntity,
        create: CreatePost,
        update: UpdatePost,
        schema: POSTS_SCHEMA,
        plain: {
            POST_ID => ID: PostId = FIELD_ID,
            POST_TITLE => TITLE: String = "title",
            POST_CONTENT => CONTENT: Option<String> = "content",
            POST_AUTHOR => AUTHOR: String = "author",
        },
        encoded: {
        }
    }
    nx_db::impl_relation_one! { rel_const: POST_AUTHOR_REL, populate_const: POST_AUTHOR_POPULATE, rel_expr: nx_db::Rel::<Post, User>::many_to_one("author", "author"), local_fn: populate_post_author_local_key, remote_fn: populate_post_author_remote_key, set_fn: populate_post_author_set, model: Post, related_model: User, entity: PostEntity, related_entity: UserEntity, field: author_rel, local_key: |local_entity| Some(local_entity.author.clone()), remote_key: |remote_entity| Some(remote_entity.id.to_string()) }

    const POSTS_ATTRIBUTES: &[AttributeSchema] = &[
        AttributeSchema::persisted("title", "title", AttributeKind::String).required(),
        AttributeSchema::persisted("content", "content", AttributeKind::String),
        AttributeSchema::persisted("author", "author", AttributeKind::Relationship).required().relationship(nx_db::RelationshipSchema::new("users", nx_db::RelationshipKind::ManyToOne, nx_db::RelationshipSide::Parent)),
    ];
    const POSTS_INDEXES: &[nx_db::IndexSchema] = &[
        nx_db::IndexSchema::new("full_text_content", nx_db::IndexKind::FullText, &["content"]),
    ];
    pub static POSTS_SCHEMA: CollectionSchema = CollectionSchema::new("posts", "Posts").document_security(true).permissions(&["read(\"any\")", "create(\"any\")"]).attributes(POSTS_ATTRIBUTES).indexes(POSTS_INDEXES);
    nx_db::impl_registry_fn! {
        fn: registry,
        schemas: [
            USERS_SCHEMA,
            POSTS_SCHEMA,
        ]
    }
}
