// @generated by database-cli.
// Do not edit by hand.

pub mod prod_models {
    use database::traits::storage::StorageRecord;
    use database::{insert_value, take_optional, take_required, AttributeKind, AttributePersistence, AttributeSchema, CollectionSchema, Context, DatabaseError, Field, Key, Model, Patch, StaticRegistry};

    pub type UserId = Key<32>;

    #[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
    pub struct UserEntity {
        pub id: UserId,
        pub name: String,
        pub email: String,
        pub metadata: Option<String>,
    }

    #[derive(Debug, Clone)]
    pub struct CreateUser {
        pub id: UserId,
        pub name: String,
        pub email: String,
        pub metadata: Option<String>,
    }

    #[derive(Debug, Clone, Default)]
    pub struct UpdateUser {
        pub name: Patch<String>,
        pub email: Patch<String>,
        pub metadata: Patch<Option<String>>,
    }

    #[derive(Debug, Clone, Copy)]
    pub struct User;
    pub const USER: User = User;

    pub const USER_ID: Field<User, UserId> = Field::new(database::FIELD_ID);
    pub const USER_NAME: Field<User, String> = Field::new("name");
    pub const USER_EMAIL: Field<User, String> = Field::new("email");
    pub const USER_METADATA: Field<User, Option<String>> = Field::new("metadata");

    const USERS_ATTRIBUTES: &[AttributeSchema] = &[
        AttributeSchema {
            id: "name",
            column: "name",
            kind: AttributeKind::String,
            required: true,
            array: false,
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: None,
        },
        AttributeSchema {
            id: "email",
            column: "email",
            kind: AttributeKind::String,
            required: true,
            array: false,
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: None,
        },
        AttributeSchema {
            id: "metadata",
            column: "metadata",
            kind: AttributeKind::Json,
            required: false,
            array: false,
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: None,
        },
    ];

    const USERS_INDEXES: &[database::IndexSchema] = &[
        database::IndexSchema {
            id: "users_email_unique",
            kind: database::IndexKind::Unique,
            attributes: &["email"],
            orders: &[],
        },
    ];

    pub static USERS_SCHEMA: CollectionSchema = CollectionSchema {
        id: "users",
        name: "Users",
        document_security: true,
        enabled: true,
        permissions: &["read(\"any\")", "create(\"any\")"],
        attributes: USERS_ATTRIBUTES,
        indexes: USERS_INDEXES,
    };

    impl Model for User {
        type Id = UserId;
        type Entity = UserEntity;
        type Create = CreateUser;
        type Update = UpdateUser;

        fn schema() -> &'static CollectionSchema {
            &USERS_SCHEMA
        }

        fn entity_to_id(entity: &Self::Entity) -> &Self::Id {
            &entity.id
        }

        fn create_to_record(input: Self::Create, _context: &Context) -> Result<StorageRecord, DatabaseError> {
            let mut record = StorageRecord::new();
            insert_value(&mut record, database::FIELD_ID, input.id);
            insert_value(&mut record, "name", input.name);
            insert_value(&mut record, "email", input.email);
            if let Some(value) = input.metadata { insert_value(&mut record, "metadata", value); }
            Ok(record)
        }

        fn update_to_record(input: Self::Update, _context: &Context) -> Result<StorageRecord, DatabaseError> {
            let mut record = StorageRecord::new();
            if let Patch::Set(value) = input.name { insert_value(&mut record, "name", value); }
            if let Patch::Set(value) = input.email { insert_value(&mut record, "email", value); }
            if let Patch::Set(value) = input.metadata { insert_value(&mut record, "metadata", value); }
            Ok(record)
        }

        fn entity_from_record(mut record: StorageRecord, _context: &Context) -> Result<Self::Entity, DatabaseError> {
            Ok(UserEntity {
                id: take_required(&mut record, database::FIELD_ID)?,
                name: take_required(&mut record, "name")?,
                email: take_required(&mut record, "email")?,
                metadata: take_optional(&mut record, "metadata")?,
            })
        }
    }

    pub type PostId = Key<32>;

    #[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
    pub struct PostEntity {
        pub id: PostId,
        pub title: String,
        pub content: Option<String>,
        pub author: String,
    }

    #[derive(Debug, Clone)]
    pub struct CreatePost {
        pub id: PostId,
        pub title: String,
        pub content: Option<String>,
        pub author: String,
    }

    #[derive(Debug, Clone, Default)]
    pub struct UpdatePost {
        pub title: Patch<String>,
        pub content: Patch<Option<String>>,
        pub author: Patch<String>,
    }

    #[derive(Debug, Clone, Copy)]
    pub struct Post;
    pub const POST: Post = Post;

    pub const POST_ID: Field<Post, PostId> = Field::new(database::FIELD_ID);
    pub const POST_TITLE: Field<Post, String> = Field::new("title");
    pub const POST_CONTENT: Field<Post, Option<String>> = Field::new("content");
    pub const POST_AUTHOR: Field<Post, String> = Field::new("author");

    const POSTS_ATTRIBUTES: &[AttributeSchema] = &[
        AttributeSchema {
            id: "title",
            column: "title",
            kind: AttributeKind::String,
            required: true,
            array: false,
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: None,
        },
        AttributeSchema {
            id: "content",
            column: "content",
            kind: AttributeKind::String,
            required: false,
            array: false,
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: None,
        },
        AttributeSchema {
            id: "author",
            column: "author",
            kind: AttributeKind::Relationship,
            required: true,
            array: false,
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: Some(database::RelationshipSchema {
                related_collection: "users",
                kind: database::RelationshipKind::ManyToOne,
                side: database::RelationshipSide::Parent,
                two_way: false,
                two_way_key: None,
                on_delete: database::OnDeleteAction::Restrict,
            }),
        },
    ];

    const POSTS_INDEXES: &[database::IndexSchema] = &[
    ];

    pub static POSTS_SCHEMA: CollectionSchema = CollectionSchema {
        id: "posts",
        name: "Posts",
        document_security: true,
        enabled: true,
        permissions: &["read(\"any\")", "create(\"any\")"],
        attributes: POSTS_ATTRIBUTES,
        indexes: POSTS_INDEXES,
    };

    impl Model for Post {
        type Id = PostId;
        type Entity = PostEntity;
        type Create = CreatePost;
        type Update = UpdatePost;

        fn schema() -> &'static CollectionSchema {
            &POSTS_SCHEMA
        }

        fn entity_to_id(entity: &Self::Entity) -> &Self::Id {
            &entity.id
        }

        fn create_to_record(input: Self::Create, _context: &Context) -> Result<StorageRecord, DatabaseError> {
            let mut record = StorageRecord::new();
            insert_value(&mut record, database::FIELD_ID, input.id);
            insert_value(&mut record, "title", input.title);
            if let Some(value) = input.content { insert_value(&mut record, "content", value); }
            insert_value(&mut record, "author", input.author);
            Ok(record)
        }

        fn update_to_record(input: Self::Update, _context: &Context) -> Result<StorageRecord, DatabaseError> {
            let mut record = StorageRecord::new();
            if let Patch::Set(value) = input.title { insert_value(&mut record, "title", value); }
            if let Patch::Set(value) = input.content { insert_value(&mut record, "content", value); }
            if let Patch::Set(value) = input.author { insert_value(&mut record, "author", value); }
            Ok(record)
        }

        fn entity_from_record(mut record: StorageRecord, _context: &Context) -> Result<Self::Entity, DatabaseError> {
            Ok(PostEntity {
                id: take_required(&mut record, database::FIELD_ID)?,
                title: take_required(&mut record, "title")?,
                content: take_optional(&mut record, "content")?,
                author: take_required(&mut record, "author")?,
            })
        }
    }

    pub fn registry() -> Result<StaticRegistry, DatabaseError> {
        let registry = StaticRegistry::new()
            .register(&USERS_SCHEMA)?
            .register(&POSTS_SCHEMA)?
            ;
        Ok(registry)
    }
}
