// @generated by database-cli.
// Do not edit by hand.

#[allow(dead_code)]
#[allow(unused_imports)]
pub mod prod_models {
    use nx_db::traits::storage::StorageRecord;
    use nx_db::{
        AttributeKind, AttributePersistence, AttributeSchema, CollectionSchema, Context,
        DatabaseError, FIELD_CREATED_AT, FIELD_ID, FIELD_PERMISSIONS, FIELD_SEQUENCE,
        FIELD_UPDATED_AT, Field, Key, Model, Patch, QuerySpec, RelationshipKind,
        RelationshipSchema, RelationshipSide, StaticRegistry, get_optional, get_required,
        insert_value, take_optional, take_required,
    };

    pub type UserId = Key<32>;

    #[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
    pub struct UserEntity {
        pub id: UserId,
        pub name: String,
        pub email: String,
        pub metadata: Option<String>,
        pub _metadata: nx_db::Metadata,
    }

    #[derive(Debug, Clone)]
    pub struct CreateUser {
        pub id: UserId,
        pub name: String,
        pub email: String,
        pub metadata: Option<String>,
        pub permissions: Vec<String>,
    }

    #[derive(Debug, Clone, Default)]
    pub struct UpdateUser {
        pub name: Patch<String>,
        pub email: Patch<String>,
        pub metadata: Patch<Option<String>>,
        pub permissions: Patch<Vec<String>>,
    }

    #[derive(Debug, Clone, Copy)]
    pub struct User;
    pub const USER: User = User;

    pub const USER_ID: Field<User, UserId> = Field::new(FIELD_ID);
    pub const USER_NAME: Field<User, String> = Field::new("name");
    pub const USER_EMAIL: Field<User, String> = Field::new("email");
    pub const USER_METADATA: Field<User, Option<String>> = Field::new("metadata");

    const USERS_ATTRIBUTES: &[AttributeSchema] = &[
        AttributeSchema {
            id: "name",
            column: "name",
            kind: AttributeKind::String,
            required: true,
            array: false,
            length: None,
            default: None,
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: None,
        },
        AttributeSchema {
            id: "email",
            column: "email",
            kind: AttributeKind::String,
            required: true,
            array: false,
            length: None,
            default: None,
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: None,
        },
        AttributeSchema {
            id: "metadata",
            column: "metadata",
            kind: AttributeKind::Json,
            required: false,
            array: false,
            length: None,
            default: None,
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: None,
        },
    ];
    const USERS_INDEXES: &[nx_db::IndexSchema] = &[nx_db::IndexSchema {
        id: "users_email_unique",
        kind: nx_db::IndexKind::Unique,
        attributes: &["email"],
        orders: &[],
    }];
    pub static USERS_SCHEMA: CollectionSchema = CollectionSchema {
        id: "users",
        name: "Users",
        document_security: true,
        enabled: true,
        permissions: &["read(\"any\")", "create(\"any\")"],
        attributes: USERS_ATTRIBUTES,
        indexes: USERS_INDEXES,
    };
    impl User {
        pub const ID: Field<User, UserId> = Field::new(FIELD_ID);
        pub const NAME: Field<User, String> = Field::new("name");
        pub const EMAIL: Field<User, String> = Field::new("email");
        pub const METADATA: Field<User, Option<String>> = Field::new("metadata");
    }
    nx_db::impl_model! { name: User, id: UserId, entity: UserEntity, create: CreateUser, update: UpdateUser, schema: USERS_SCHEMA, fields: {                 "name" => name : String :required,                 "email" => email : String :required,                 "metadata" => metadata : Option<String> } }
    pub type PostId = Key<32>;

    #[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
    pub struct PostEntity {
        pub id: PostId,
        pub title: String,
        pub content: Option<String>,
        pub author: String,
        pub _metadata: nx_db::Metadata,
    }

    #[derive(Debug, Clone)]
    pub struct CreatePost {
        pub id: PostId,
        pub title: String,
        pub content: Option<String>,
        pub author: String,
        pub permissions: Vec<String>,
    }

    #[derive(Debug, Clone, Default)]
    pub struct UpdatePost {
        pub title: Patch<String>,
        pub content: Patch<Option<String>>,
        pub author: Patch<String>,
        pub permissions: Patch<Vec<String>>,
    }

    #[derive(Debug, Clone, Copy)]
    pub struct Post;
    pub const POST: Post = Post;

    pub const POST_ID: Field<Post, PostId> = Field::new(FIELD_ID);
    pub const POST_TITLE: Field<Post, String> = Field::new("title");
    pub const POST_CONTENT: Field<Post, Option<String>> = Field::new("content");
    pub const POST_AUTHOR: Field<Post, String> = Field::new("author");

    const POSTS_ATTRIBUTES: &[AttributeSchema] = &[
        AttributeSchema {
            id: "title",
            column: "title",
            kind: AttributeKind::String,
            required: true,
            array: false,
            length: None,
            default: None,
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: None,
        },
        AttributeSchema {
            id: "content",
            column: "content",
            kind: AttributeKind::String,
            required: false,
            array: false,
            length: None,
            default: None,
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: None,
        },
        AttributeSchema {
            id: "author",
            column: "author",
            kind: AttributeKind::Relationship,
            required: true,
            array: false,
            length: None,
            default: None,
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: Some(nx_db::RelationshipSchema {
                related_collection: "users",
                kind: nx_db::RelationshipKind::ManyToOne,
                side: nx_db::RelationshipSide::Parent,
                two_way: false,
                two_way_key: None,
                on_delete: nx_db::OnDeleteAction::Restrict,
            }),
        },
    ];
    const POSTS_INDEXES: &[nx_db::IndexSchema] = &[nx_db::IndexSchema {
        id: "full_text_content",
        kind: nx_db::IndexKind::FullText,
        attributes: &["content"],
        orders: &[],
    }];
    pub static POSTS_SCHEMA: CollectionSchema = CollectionSchema {
        id: "posts",
        name: "Posts",
        document_security: true,
        enabled: true,
        permissions: &["read(\"any\")", "create(\"any\")"],
        attributes: POSTS_ATTRIBUTES,
        indexes: POSTS_INDEXES,
    };
    impl Post {
        pub const ID: Field<Post, PostId> = Field::new(FIELD_ID);
        pub const TITLE: Field<Post, String> = Field::new("title");
        pub const CONTENT: Field<Post, Option<String>> = Field::new("content");
        pub const AUTHOR: Field<Post, String> = Field::new("author");
    }
    nx_db::impl_model! { name: Post, id: PostId, entity: PostEntity, create: CreatePost, update: UpdatePost, schema: POSTS_SCHEMA, fields: {                 "title" => title : String :required,                 "content" => content : Option<String>,                 "author" => author : String :required } }
    pub fn registry() -> Result<StaticRegistry, DatabaseError> {
        let registry = StaticRegistry::new()
            .register(&USERS_SCHEMA)?
            .register(&POSTS_SCHEMA)?;
        Ok(registry)
    }
}
