// @generated by database-cli.
// Do not edit by hand.

pub mod virtual_app_models {
    use nx_db::traits::storage::StorageRecord;
    use nx_db::{insert_value, take_required, AttributeKind, AttributePersistence, AttributeSchema, CollectionSchema, Context, DatabaseError, ModelFuture, Field, Key, Model, Patch, StaticRegistry};

    pub type UserId = Key<32>;

    #[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
    pub struct UserEntity {
        pub id: UserId,
        pub name: String,
        pub active: bool,
        pub profile_label: Option<String>,
    }

    #[derive(Debug, Clone)]
    pub struct CreateUser {
        pub id: UserId,
        pub name: String,
        pub active: bool,
    }

    #[derive(Debug, Clone, Default)]
    pub struct UpdateUser {
        pub name: Patch<String>,
        pub active: Patch<bool>,
    }

    #[derive(Debug, Clone, Copy)]
    pub struct User;
    pub const USER: User = User;

    pub const USER_ID: Field<User, UserId> = Field::new(nx_db::FIELD_ID);
    pub const USER_NAME: Field<User, String> = Field::new("name");
    pub const USER_ACTIVE: Field<User, bool> = Field::new("active");

    const USERS_ATTRIBUTES: &[AttributeSchema] = &[
        AttributeSchema {
            id: "name",
            column: "name",
            kind: AttributeKind::String,
            required: true,
            array: false,
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: None,
        },
        AttributeSchema {
            id: "active",
            column: "active",
            kind: AttributeKind::Boolean,
            required: true,
            array: false,
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: None,
        },
        AttributeSchema {
            id: "profileLabel",
            column: "",
            kind: AttributeKind::Virtual,
            required: false,
            array: false,
            persistence: AttributePersistence::Virtual,
            filters: &[],
            relationship: None,
        },
    ];

    const USERS_INDEXES: &[nx_db::IndexSchema] = &[
    ];

    pub static USERS_SCHEMA: CollectionSchema = CollectionSchema {
        id: "users",
        name: "Users",
        document_security: true,
        enabled: true,
        permissions: &["read(\"any\")", "create(\"any\")", "update(\"any\")", "delete(\"any\")"],
        attributes: USERS_ATTRIBUTES,
        indexes: USERS_INDEXES,
    };

    impl Model for User {
        type Id = UserId;
        type Entity = UserEntity;
        type Create = CreateUser;
        type Update = UpdateUser;

        fn schema() -> &'static CollectionSchema {
            &USERS_SCHEMA
        }

        fn entity_to_id(entity: &Self::Entity) -> &Self::Id {
            &entity.id
        }

        fn create_to_record(input: Self::Create, _context: &Context) -> Result<StorageRecord, DatabaseError> {
            let mut record = StorageRecord::new();
            insert_value(&mut record, nx_db::FIELD_ID, input.id);
            insert_value(&mut record, "name", input.name);
            insert_value(&mut record, "active", input.active);
            Ok(record)
        }

        fn update_to_record(input: Self::Update, _context: &Context) -> Result<StorageRecord, DatabaseError> {
            let mut record = StorageRecord::new();
            if let Patch::Set(value) = input.name { insert_value(&mut record, "name", value); }
            if let Patch::Set(value) = input.active { insert_value(&mut record, "active", value); }
            Ok(record)
        }

        fn entity_from_record(mut record: StorageRecord, _context: &Context) -> Result<Self::Entity, DatabaseError> {
            Ok(UserEntity {
                id: take_required(&mut record, nx_db::FIELD_ID)?,
                name: take_required(&mut record, "name")?,
                active: take_required(&mut record, "active")?,
                profile_label: None,
            })
        }

        fn resolve_entity<'a>(mut entity: Self::Entity, context: &'a Context) -> ModelFuture<'a, Result<Self::Entity, DatabaseError>> {
            Box::pin(async move {
                entity.profile_label = Some(crate::resolvers::resolve_profile_label(&entity, context).await?);
                Ok(entity)
            })
        }
    }

    pub fn registry() -> Result<StaticRegistry, DatabaseError> {
        let registry = StaticRegistry::new()
            .register(&USERS_SCHEMA)?
            ;
        Ok(registry)
    }
}
