// @generated by database-cli.
// Do not edit by hand.

#[allow(dead_code)]
#[allow(unused_imports)]
pub mod virtual_app_models {
    use nx_db::traits::storage::StorageRecord;
    use nx_db::{insert_value, take_optional, take_required, get_optional, get_required, AttributeKind, AttributePersistence, AttributeSchema, CollectionSchema, Context, DatabaseError, ModelFuture, Field, Key, Model, Patch, QuerySpec, RelationshipKind, RelationshipSchema, RelationshipSide, StaticRegistry, FIELD_ID, FIELD_SEQUENCE, FIELD_CREATED_AT, FIELD_UPDATED_AT, FIELD_PERMISSIONS};

    pub type UserId = Key<32>;

    #[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
    pub struct UserEntity {
        pub id: UserId,
        pub name: String,
        pub active: bool,
        pub profile_label: Option<String>,
        pub _metadata: nx_db::Metadata,
    }

    #[derive(Debug, Clone)]
    pub struct CreateUser {
        pub id: UserId,
        pub name: String,
        pub active: bool,
        pub permissions: Vec<String>,
    }

    #[derive(Debug, Clone, Default)]
    pub struct UpdateUser {
        pub name: Patch<String>,
        pub active: Patch<bool>,
        pub permissions: Patch<Vec<String>>,
    }

    #[derive(Debug, Clone, Copy)]
    pub struct User;
    pub const USER: User = User;

    pub const USER_ID: Field<User, UserId> = Field::new(FIELD_ID);
    pub const USER_NAME: Field<User, String> = Field::new("name");
    pub const USER_ACTIVE: Field<User, bool> = Field::new("active");

    const USERS_ATTRIBUTES: &[AttributeSchema] = &[
        AttributeSchema {
            id: "name",
            column: "name",
            kind: AttributeKind::String,
            required: true,
            array: false,
            length: None,
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: None,
        },
        AttributeSchema {
            id: "active",
            column: "active",
            kind: AttributeKind::Boolean,
            required: true,
            array: false,
            length: None,
            persistence: AttributePersistence::Persisted,
            filters: &[],
            relationship: None,
        },
        AttributeSchema {
            id: "profileLabel",
            column: "",
            kind: AttributeKind::Virtual,
            required: false,
            array: false,
            length: None,
            persistence: AttributePersistence::Virtual,
            filters: &[],
            relationship: None,
        },
    ];
    const USERS_INDEXES: &[nx_db::IndexSchema] = &[
    ];
    pub static USERS_SCHEMA: CollectionSchema = CollectionSchema { id: "users", name: "Users", document_security: true, enabled: true, permissions: &["read(\"any\")", "create(\"any\")", "update(\"any\")", "delete(\"any\")"], attributes: USERS_ATTRIBUTES, indexes: USERS_INDEXES };
    impl User {
        pub const ID: Field<User, UserId> = Field::new(FIELD_ID);
        pub const NAME: Field<User, String> = Field::new("name");
        pub const ACTIVE: Field<User, bool> = Field::new("active");
    }
    nx_db::impl_model! { name: User, id: UserId, entity: UserEntity, create: CreateUser, update: UpdateUser, schema: USERS_SCHEMA, fields: {                 "name" => name : String :required,                 "active" => active : bool :required }, virtuals: { profile_label }, resolvers: { profile_label : crate::resolvers::resolve_profile_label } }
    pub fn registry() -> Result<StaticRegistry, DatabaseError> {
        let registry = StaticRegistry::new()
            .register(&USERS_SCHEMA)?
            ;
        Ok(registry)
    }
}
