// @generated by database-cli.
// Do not edit by hand.

#[allow(dead_code)]
pub mod virtual_app_models {
    use nx_db::{AttributeKind, AttributeSchema, CollectionSchema, Key, Patch, FIELD_ID};

    pub type UserId = Key<48>;

    #[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize, nx_db::NxEntity)]
    #[serde(rename_all = "camelCase")]
    pub struct UserEntity {
        #[nx(id)]
        pub id: UserId,
        #[nx(field = "name", required)]
        pub name: String,
        #[nx(field = "active", required)]
        pub active: bool,
        #[serde(skip_serializing_if = "Option::is_none")]
        #[nx(virtual, resolve = "crate::resolvers::resolve_profile_label")]
        pub profile_label: Option<String>,
        #[serde(rename = "_metadata")]
        #[nx(metadata)]
        pub _metadata: nx_db::Metadata,
    }

    #[derive(Debug, Clone, ::serde::Serialize, ::serde::Deserialize, nx_db::NxCreate)]
    #[serde(rename_all = "camelCase")]
    pub struct CreateUser {
        #[nx(id)]
        pub id: Option<UserId>,
        #[nx(field = "name", required)]
        pub name: String,
        #[nx(field = "active", required)]
        pub active: bool,
        #[serde(default, skip_serializing_if = "Vec::is_empty")]
        #[nx(permissions)]
        pub permissions: Vec<String>,
    }

    #[derive(Debug, Clone, Default, nx_db::NxUpdate)]
    pub struct UpdateUser {
        #[nx(field = "name")]
        pub name: Patch<String>,
        #[nx(field = "active")]
        pub active: Patch<bool>,
        #[nx(permissions)]
        pub permissions: Patch<Vec<String>>,
    }

    nx_db::declare_model! {
        name: User,
        const: USER,
        entity: UserEntity,
        create: CreateUser,
        update: UpdateUser,
        schema: USERS_SCHEMA,
        plain: {
            USER_ID => ID: UserId = FIELD_ID,
            USER_NAME => NAME: String = "name",
            USER_ACTIVE => ACTIVE: bool = "active",
        },
        encoded: {
        }
    }

    const USERS_ATTRIBUTES: &[AttributeSchema] = &[
        AttributeSchema::persisted("name", "name", AttributeKind::String).required(),
        AttributeSchema::persisted("active", "active", AttributeKind::Boolean).required(),
        AttributeSchema::virtual_field("profileLabel", AttributeKind::Virtual),
    ];
    const USERS_INDEXES: &[nx_db::IndexSchema] = &[
    ];
    pub static USERS_SCHEMA: CollectionSchema = CollectionSchema::new("users", "Users").document_security(true).permissions(&["read(\"any\")", "create(\"any\")", "update(\"any\")", "delete(\"any\")"]).attributes(USERS_ATTRIBUTES).indexes(USERS_INDEXES);
    nx_db::impl_registry_fn! {
        fn: registry,
        schemas: [
            USERS_SCHEMA,
        ]
    }
}
